### ISSUE TITLE
~ notation not behaving with 2 segements

### ISSUE THREAD

**Issue by scott2449** [npm/node-semver#11]
v.satisfies('1.4.7','~1.2') should return true based on docs:

~1.2 := >=1.2.0 <2.0.0

instead it returns false

**Comment by Linden-Ryuujin** [comment]
I understand this is long closed - but why was this decided? It seems to me like the original docs were correct (they're what I expected). Right now Tilde behaves differently for different ranges:

~1.2.3 matches to the next minor change (one version up from what is specified)
~1.2 also matches to the next minor change (the same as the version specified).

Right now there is no single operator way to describe the [1.2 > x < 2.0] while there are three for [1.2 > x < 1.3]:

1.2.x
~1.2.0
~1.2

**Comment by bminer** [comment]
`^1.2` should match `1.2 >= x < 2.0`
See https://semver.npmjs.com/

**Comment by Linden-Ryuujin** [comment]
> You can think of ~ (tilde) as "upgrade patch only"
Unless you do ~1 of course. I expected to to mean "compatible" with - similar caret without the special casing leading zeros (for me I think caret will work, as we're luckily past version 0). But I think I can now see it's kind of a reverse ordered caret. I still think it's odd, and the original documented definition would have made more sense, but I can see that ship has sailed :) Thanks for taking the time to answer me, it's appreciated.

**Comment by isaacs** [comment]
@Linden-Ryuujin Huh, yeah, `~1` is effectively the same as `1.x.x`.  That feels wrong to me.  I'd expect it would be the same as `~1.0.0`.

Since `^` is more popular anyway, it'd probably do more harm than good to change the behavior of `~1`.

**Comment by isaacs** [comment]
(Also this issue is 5 years old.  Let's let it rest in peace.)
