### ISSUE TITLE
Extract major, minor, patch version

### ISSUE THREAD

**Issue by Michenux** [npm/node-semver#115]
Hi,

Could you add some methods in the api to extract major/minor/patch ?

For example : 
sem.major('1.2.3') => 1
sem.minor('1.2.3') => 2
sem.patch('1.2.3') => 3
sem.trimMinor('1.2.3') => 1.2

Thanks

**Comment by isaacs** [comment]
Sounds reasonable. Patch welcome.

**Comment by Hypercubed** [comment]
I submitted a pull request for this feature... although it is really just sugar for `new SemVer('1.2.3').major;`, etc.

**Comment by JamesMGreene** [comment]
@Hypercubed's PR #116 was released a while ago in [`v4.3.0`](https://github.com/npm/node-semver/releases/tag/v4.3.0). 

Seems like this issue should be closed.

**Comment by isaacs** [comment]
Thanks!
