### ISSUE TITLE
Pre-release version in v4

### ISSUE THREAD

**Issue by chris-t-reilly** [npm/node-semver#118]
I'm having trouble understanding how the pre-releases are supposed to work. So far I've reached the conclusion that a pre-release version will only match a version of the same XYZ tuple (so, '1.2.4-1' and '1.2.4-2') but I can't see how to set the semver that would allow matching pre-releases outside of the XYZ tuple (e.g. '1.2.4-1' and '1.2.3').

In our development environments we use pre-releases to test new functionality, but this new behaviour doesn't allow NPM to resolve a pre-release outside of its tuple, so we get a EPEERINVALID error.

I've had a look at the source code, and I think it's related to this commit: https://github.com/npm/node-semver/commit/2331a9ebaa22e9b9c86be6105ea3cbebe7aefab5.

I'm using NPM 2.4.1 with SemVer 4.0.0

**Comment by thegiantbeast** [comment]
cc @isaacs

**Comment by isaacs** [comment]
If you want to allow `1.2.3` and `1.2.4-1`, you could do something like: `~1.2.3 || ~1.2.4-0`.

This is particularly tricky with peerDependencies, because of how peerDeps can cause dependency hell, so you end up having to update a whole bunch of things.  Probably the best would be if we had a way to just ignore invalid peers.

**Comment by carlosouro** [comment]
Hi,

I also have this use case in peerDependencies:
My component A depends on B and C, and C has a peerDependency on B.

A:
```JavaScript
dependencies:{
    "B":"1.2.0-1", //I want to test my pre-release component
    "C":"1.0.0"
}
```
C:
```JavaScript
peerDependencies:{
    "B":">=1.0.0"
}
```

This used to resolve prior to npm 2.4.1 and now it fails - I've tracked the change to the same commit mentioned above.

Agree with the concept of ignoring invalid peer errors - any suggested syntax/option we can pull request for npm?
