### ISSUE TITLE
IE8 support

### ISSUE THREAD

**Issue by matthewp** [npm/node-semver#121]
Would you accept a patch to use polyfills for [].map, [].filter, etc. to support IE8?

**Comment by othiym23** [comment]
If you can work it into the build process for the browser, sure thing.

**Comment by matthewp** [comment]
I was thinking more like:

```js
var map = Array.prototype.map || function() ...
```

To prevent setting [].map.

**Comment by othiym23** [comment]
The problem with that is that the npm developers (hi!) are pretty Node-focused, and my fear is that we would come in to "clean this up" and completely overlook the fact that browser code is depending on this. If it's part of the browser build, that's much less likely to happen.

**Comment by matthewp** [comment]
I understand your point, happy to accommodate, just need to figure out a way to do this.

Perhaps in semver.js at the top there would be

```js
var map = Array.prototype.map;
var filter = Array.prototype.filter;
var trim = String.prototype.trim;
```

And then in the browser build those get replaced by the `var map = Array.prototype.map || function() ...` varieties. How does that sound?

**Comment by isaacs** [comment]
I'm sorry, IE 8 shims do not belong in this module.

Can you use a polyfill that adds these bits and is only loaded by IE 8?

**Comment by isaacs** [comment]
A polyfill for IE8 would be a module that does:

```javascript
if (!Array.prototype.map) {
  Array.prototype.map = function (...) {...}
}
...
```

**Comment by matthewp** [comment]
In application code I can do that, but not in a library. I hope you will reconsider.
