### ISSUE TITLE
Tilde anchor not working on npmjs.com

### ISSUE THREAD

**Issue by IanVS** [npm/node-semver#122]
Super minor issue, but I was trying to share a link to the tilde explanation on npmjs.com (https://www.npmjs.com/package/semver#tilde-ranges-~123-~12-~1) and noticed that (at least in IE11), the anchor does not work.  

The anchor on github strips out the tildes (https://github.com/npm/node-semver#tilde-ranges-123-12-1) which works correctly, and I'm guessing this is what should be done on npmjs.com as well.

**Comment by isaacs** [comment]
I think this is actually a npmjs.com and/or marky-markdown issue.

@rockbot @zeke what say you?
