### ISSUE TITLE
"*" is satisfied by versions with a pre-release

### ISSUE THREAD

**Issue by adamreeve** [npm/node-semver#123]
In the range tests there's this test:
```
['*', 'v1.2.3-foo', true]
```

Which indicates that the version `1.2.3-foo` will satisfy the range `*`. But this behaviour goes against what is described in the README, which says that:

> If a version has a prerelease tag (for example, 1.2.3-alpha.3) then it will only be allowed to satisfy comparator sets if at least one comparator with the same [major, minor, patch] tuple also has a prerelease tag.

I can't find anywhere that states that X-ranges allow pre-release versions. I would expect that `1.2.3-foo` would not satisfy `*`, but if this is the expected behaviour, then it should be documented.

Also, if `*` is satisfied by `1.2.3-foo`, then why is `1.*` not satisfied by `1.2.3-foo`? This behaviour seems inconsistent.

**Comment by isaacs** [comment]
Indeed, this is a bug.  Patch welcome (including patch that is just a failing test, since that'll drive me crazy until the tests pass again ;)

**Comment by qzb** [comment]
I agree that this behaviour is inconsistent so should be changed, but on the other hand it's very useful. There are some projects maintained by people who doesn't understand how semver works which have prerelease tags in their stable release versions (e.g. node-zookeeper). This behaviour could be used to workaround this issues.

**Comment by benjamn** [comment]
This turned out to be a breaking change for the `read-installed` package, which `npm` uses: https://github.com/npm/read-installed/issues/40

I think the problem can be fixed on their end, but I thought I would surface it here, in case anyone here thinks this issue can be addressed more conservatively.
