### ISSUE TITLE
[idea] semver.max(array versions)

### ISSUE THREAD

**Issue by trusktr** [npm/node-semver#128]
Would return the greatest version found in the array.

**Comment by isaacs** [comment]
You can already do this a few different ways

```
var versions = [ '1.2.3', '3.4.5', '1.0.2' ]
var max = versions.sort(semver.rcompare)[0]
var min = versions.sort(semver.compare)[0]
var max = semver.maxSatisfying(versions, '*')
```

**Comment by trusktr** [comment]
Sweet. I forgot about `*` and was thinking "How would I know what versions to specify?" Thanks!

**Comment by mbrevda** [comment]
Can this be done from the cli?
