### ISSUE TITLE
Confusingly named

### ISSUE THREAD

**Issue by JasperHorn** [npm/node-semver#129]
I understand that there are enough reasons not to change the name of this package (mainly the normal reasons to avoid changing the name of a package) but since the issue hasn't been raised yet, I decided to report it anyway.

Basically, the name of this github repository already betrays the problem: this is not semver. Semver is http://semver.org, this is just a tool that uses semver. node-semver actually makes a lot of sense, as it is the implementation node uses to interpret semver version (while adding a new syntax to define version ranges).

(I actually thought the node documentation was referring to [semver](http://semver) when they actually meant [semver](https://github.com/npm/node-semver) here: https://github.com/npm/npm/issues/8663)

**Comment by isaacs** [comment]
Sure.

In the context of Node programs, `require("semver")` returns the node implementation of semver parsing.  If it returned a markdown website, then that'd be bizarre and wrong.  Putting `node-` on the start of that name would be excessive.

So, in the context of GitHub, `node-semver` makes sense, but the package name is just `semver`, because disambiguation is not necessary in that context.

**Comment by JasperHorn** [comment]
I disagree.

`require("cordova")` doesn't return me a package that node itself uses. As such, the "node-"preffix does add information. Or maybe "npm-semver" would make more sense (I just copied "node-semver" name from this repository).

Say I would make my own program related in some way to semver and call it `smvr`. Now there's `semver` and `smvr`, but it's pure guesswork which one is the one that is used to parse you package.json. `npm-semver` actually removes all of that ambiguity...

However, even if we work under the assumption that adding "npm-" or "node-" makes no sense, being called just "semver" still doesn't make sense. I'll agree that suddenly getting a markdown website (or more abstractly, a specification) in your javascript program makes no sense. However semver *is* a markdown website (or more accurately, a specification) so you shouldn't be returning something else either. Ergo, `require("semver")` makes no sense semantically at all. It would be better if it didn't work.

As you mention, this package is "an implementation of semver parsing". It isn't *even* an implementation of semver. No, it's an implementation of a parser.(of semver). So, even we do believe that it will magically be clear that this package is tied to npm, "semver-parser" makes more sense than just "semver".

**Comment by isaacs** [comment]
This isn't just a parser, though.  It's also a tool for manipulating, sorting, and analyzing semver versions and ranges.  So, `semver-parser` isn't really correct.

Whatever the case, we aren't going to rename this package.  Many people are depending on it, and do not find its name confusing.

Thanks.  Is there anything else that we can do to help alleviate the confusion for you?

**Comment by JasperHorn** [comment]
`semver-tools`, `semver-utils`?

I think it's interesting that you keep attacking the alternatives I suggest off the top of my head without ever defending the current name. Sure, you can show that my suggestions aren't "completely correct", but that does not respond at all to my core claim, which is that the current name is completely incorrect.

I guess mostly wanted the issue to be above the table, even if there are good reasons to not do anything about it. This is especially important because people often assume that if someone doesn't report the issue, it doesn't exist (like when you assume that anyone who uses the package without mentioning confusion does not find its name confusing).

But yeah, as I said in my very first sentence, there are good reasons not to rename a package...
