### ISSUE TITLE
how to use semver.compare with array.sort

### ISSUE THREAD

**Issue by divramod** [npm/node-semver#131]
i try to sort the tags in my git repository.
could someone give me the right syntax?

i tried: 

        // i am using shelljs to get the tags
        var lines = exec('git tag', {
            silent: false
        }).output;

       var tags = lines.split(/\r?\n/);  // splitting to lines to an array
       tags.pop(); // for removing the empty line at the end
       tags.sort(semver.compare());  // which parameters do i have to choose?

**Comment by megawac** [comment]
`tags.sort(semver.compare)`

**Comment by divramod** [comment]
thx, that solved it

**Comment by dukedougal** [comment]
It would be good if this example was in the front page documentation.  It's hard to divine the syntax.

**Comment by isaacs** [comment]
Doc patch welcome!
