### ISSUE TITLE
semver.satisfies has an incorrect return when the second argument has "x" as the MINOR number.

### ISSUE THREAD

**Issue by printnode-jake** [npm/node-semver#132]
``` javascript
console.log(semver.satisfies("4.4.2","4.x.1"))
//this is true, should be false
```

**Comment by anko** [comment]
Given that a patch version `4.1.1` isn't defined in semver to be in any way related to `4.2.1`, why would you want to do that?

I think `satisfies`-targets of the form `1.x.1` or `x.x.1` should fail to parse.

**Comment by isaacs** [comment]
Yeah, I'm inclined to agree.  `4.x.1` isn't a thing.  The `x` ends the range.  It's not a `*` glob pattern thing.

**Comment by isaacs** [comment]
Closing.  4.x.1 is 4.x.
