### ISSUE TITLE
README lacks documentation on clean() function

### ISSUE THREAD

**Issue by konobi** [npm/node-semver#134]
There's no documentation associated with the clean() function. I'm currently looking to see if a list of dependency declarations are at least "valid". Is this what the clean() function provides?

**Comment by isaacs** [comment]
`clean` returns either the canonicalized version in `X.Y.Z-prerelease` format, or `null` if it can't be parsed.  The second `loose` boolean argument makes it looser in what it accepts.

Doc patch welcome.

```
> s.clean(' = v 2.1.5foo')
null
> s.clean(' = v 2.1.5foo', true)
'2.1.5-foo'
> s.clean(' = v 2.1.5-foo')
null
> s.clean(' = v 2.1.5')
null
> s.clean('=v2.1.5')
'2.1.5'
> s.clean('  =v2.1.5')
'2.1.5'
> s.clean('      2.1.5   ')
'2.1.5'
```

**Comment by 1j01** [comment]
Also of note, `clean` doesn't work with ranges.
```
> semver.clean('~1.0.0')
null
```
`validRange` can return a cleaned up range, although it also makes it verbose and explicit.
```
> semver.validRange('   ~ 1.0.0 ')
'>=1.0.0 <1.1.0'
```
