### ISSUE TITLE
inc does not update raw

### ISSUE THREAD

**Issue by mariusGundersen** [npm/node-semver#137]
using the `inc` method on a semver object does not update the raw value:

```js
console.log(semver.parse('1.2.3').inc('minor').raw === '1.2.3');

var version = semver.parse('1.2.3');
//{
//  "raw": "1.2.3",
//  "major": 1,
//  "minor": 2,
//  "patch": 3,
//  "prerelease": [],
//  "build": [],
//  "version": "1.2.3"
//}
version.inc('minor')
//{
//  "raw": "1.2.3",
//  "major": 1,
//  "minor": 3,
//  "patch": 0,
//  "prerelease": [],
//  "build": [],
//  "version": "1.3.0"
//}
```

This is a bit surprising. Shouldn't raw either be updated or removed?

**Comment by isaacs** [comment]
I would call that a bug, indeed.

The `raw` field should probably be set equal to `version` when `inc()` is called.  It's only there to track what you originally put there, and when you call `inc` you're explicitly declaring that the original input is no longer what you want.
