### ISSUE TITLE
Caret version donut hole?

### ISSUE THREAD

**Issue by theganyo** [npm/node-semver#155]
If I have a minor version that is zero but non-zero major and patch versions, the caret version doesn't work as I would expect. Instead of just allowing patches, it allows minor revisions. For example, a range specification of "^5.0.4":

semver '5.0.1' -r '^5.0.4' ->
semver '5.0.9' -r '^5.0.4' -> 5.0.9
semver '5.1.1' -r '^5.0.4' -> 5.1.1
semver '5.9.0' -r '^5.0.4' -> 5.9.0
semver '6.0.0' -r '^5.0.4' -> 

The problem is that, by default using `npm i --save`, if I happen to get a revision 5.0.4, it will not only allow patch revisions as one would expect in every other version case (eg. if the version were 5.1.4 or 5.2.4), but it will allow all minor versions as well. This behavior seems inconsistent and likely to lead to unforeseen breakage.

**Comment by theganyo** [comment]
Actually, now I'm confused. The above was based on a report that I received. But actually, I see now that:

semver '5.5.9' -r '^5.1.4' -> 5.5.9

So maybe I'm just misinterpreting how the semver CLI works and this isn't really the issue.

I'm closing this until I figure it out.

**Comment by isaacs** [comment]
Working as designed.

The `^` operator holds the first non-zero number constant, and otherwise allows any version >= the specifier.  So `^5.0.4` is equivalent to `>=5.0.4 <6.0.0`.

Perhaps you're thinking of `~`?

**Comment by theganyo** [comment]
Thanks, @isaacs. My concern comes not from incorrect implementation, but unexpected consequences of the design of the caret. As mentioned above, using the example of npm, if I install a package using --save in npm and it happens to be at a version 5.0.4, it will have astonishingly different consequences for my dependencies than if I install a package that happens to be at version 5.1.4.

Am I thinking about this wrong?

**Comment by isaacs** [comment]
What is astonishingly different between `^5.0.4` and `^5.1.4`?  One of them is "less than 6, greater than or equal to 5.0.4".  The other is "less than 6, greater than or equal to 5.1.4".  It's not any kind of conceptual difference, just a different version that you're setting as the minimum.

**Comment by isaacs** [comment]
Or are you saying that `5.0.4` is astonishingly different from `5.1.4`, and so it's surprising that `^5.0.4` allows `5.1.4` to be installed at all?

In that case, it _should_ only be additive API changes, and you can use `~` instead of `^` to limit it more tightly.

**Comment by theganyo** [comment]
Yes, I was saying the 2nd. But you're right: That's what the `~` does, so I should just use that. Thanks for your help.
