### ISSUE TITLE
maxSatisfying didn't return the highest version for pre-version

### ISSUE THREAD

**Issue by kunyan** [npm/node-semver#156]
```javascript
var versions = ['0.1.0-rc.1', '0.1.0-rc.2'];
semver.valid(versions[0]) // 0.1.0-rc.1
semver.valid(versions[1]) // 0.1.0-rc.2

semver.maxSatisfying(versions, '*', true)  // null
```
if I add a regular version like '1.0.0', it works good
```javascript
var versions = ['0.1.0-rc.1', '0.1.0-rc.2', '1.0.0'];
semver.maxSatisfying(versions, '*', true); // 1.0.0
```

Why it can not return the highest version number for pre-version ?

**Comment by isaacs** [comment]
Working as designed.  See: https://github.com/npm/node-semver#prerelease-tags

**Comment by DoroNahari** [comment]
For peoples who encounter this "problem":
If you want maxSatisfying to include pre-release versions, you need to add the includePrerelease option to your maxSatisfying method as described here: https://github.com/npm/node-semver#functions

In the example above:

semver.maxSatisfying(versions, "*", {
        includePrerelease: true
});
