### ISSUE TITLE
The asterisk range operator doesn't include asterisks

### ISSUE THREAD

**Issue by callumlocke** [npm/node-semver#162]
The node-semver readme says:

```
* := >=0.0.0 (Any version satisfies)
```

But beta versions don't satisfy it. I'm trying to install the following two packages:

- `preact@5.0.1-beta.14`
- `preact-compat@1.8.0` (this peer-depends on `"preact": "*"`)

However, when using npm 2 (which I'm stuck with for now), I can't install these two together, because apparently the semver range `*` doesn't include `5.0.1-beta.14`. Is this a bug?

```
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package preact@5.0.1-beta.12 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer preact-compat@1.8.0 wants preact@*
```

**Comment by isaacs** [comment]
Working as designed.

**Comment by isaacs** [comment]
https://github.com/npm/node-semver#prerelease-tags

**Comment by callumlocke** [comment]
In that case, are the docs wrong?
