### ISSUE TITLE
running clean() on '2'

### ISSUE THREAD

**Issue by dxu** [npm/node-semver#170]
I found this while trying to run semver.clean() on [these](https://github.com/isaacs/node-glob/blob/master/package.json) dependencies. One of the dependencies is listed as 
```
dependencies: {
    ...
    "inherits": "2",
    ...
}
```
Currently, semver doesn't properly handle cleaning `2` and turning it into `2.0.0`, and just returns `null` instead. Is this intentional, or should this be fixed?

**Comment by isaacs** [comment]
This is intentional.  `2` is not a SemVer, it is a SemVer range.  Any version with `2` as the major would satisfy.  For example, `2.9.123` would be a satisfying version for that range.  It is not equivalent to `2.0.0`.
