### ISSUE TITLE
Support build metadata

### ISSUE THREAD

**Issue by jonathanfoster** [npm/node-semver#174]
I'd like to be able to version using build metadata like build number or commit SHA as per the [semver spec](http://semver.org/#spec-item-10).

**Comment by e-cloud** [comment]
agree with @jonathanfoster

**Comment by chrisdopuch** [comment]
+1 for this request
Adding build metadata would help to support continuous delivery
Specific item in semver spec for this request: http://semver.org/#spec-item-10

**Comment by patrickmarabeas** [comment]
What's the status?

**Comment by patrickmarabeas** [comment]
#221 Adds ability to read the build meta data

What's the expectation when creating a version? An additional param when `inc()` etc specifying the build meta array?

**Comment by arturparkhisenko** [comment]
And `semver.coerce('v1.2.3+45')` should parse the build. Currently, build property is always an empty array.

**Comment by isaacs** [comment]
@arturparkhisenko Please use `semver.parse()` not `semver.coerce()`.

Coerce is designed to find a semver string in potentially arbitrary input.  It throws out build metadata because that's not relevant to the version semantics.  If you know you have a valid semver string, then `semver.parse()` will include everything in it.

**Comment by arturparkhisenko** [comment]
@isaacs I didn't know about that :) thanks! No docs for `parse` in the readme.

**Comment by ben-xD** [comment]
> it’s not part of the unique key that represents the version.

Could you point me to the part of the spec that says that?

**Comment by ljharb** [comment]
The analogy doesn’t quite hold, i think.

I agree npm could allow build metadata to be stored, but since virtually everything else about using npm is comparing versions, it’d just be an extra step later to drop it.

**Comment by ben-xD** [comment]
Analogies never really do hold up to scrutiny 😇. What do you think the point of having build metadata is then? Wouldn't it be useful to choose the version with a specific "build metadata" string?

Take a look at @jeffhandley's blog post ["Supporting Semantic Versioning 2.0.0"](https://devblogs.microsoft.com/nuget/supporting-semver-2-0-0/#build-metadata):
> It allows the package author to embed metadata into the version number such as a commit hash, date, build number, or anything else that could be used for diagnostics.

This is from the **same** person who **updated the semver spec** via a Github PR: https://github.com/semver/semver.org/pull/58

**Comment by ljharb** [comment]
I personally don't think there is much of a point, and I think build metadata shouldn't be used - but either way, "for diagnostics" means you'd look up the build metadata *after a problem had occurred* - it wouldn't be useful until then, and when it *is* useful, it theoretically would be present inside the package.json on disk of the package.

**Comment by ben-xD** [comment]
Maybe I should clarify:
> **into** the version number 

means the version string **includes the build metadata**, rather than "the differences can be discarded" as you suggest.
