### ISSUE TITLE
provide a way to match latest prerelease

### ISSUE THREAD

**Issue by kellyselden** [npm/node-semver#175]
You have stated that prereleases are to be excluded in ranges:

> So, 1.2.3-beta.4 would be allowed, but 1.2.4-beta.2 would not, because it is a prerelease of a different [major, minor, patch] tuple.

But for prereleases (betas, canaries) that live forever and move minor versions:

``` js
devDependencies: {
  'ember-data': 'emberjs/data#beta'
}
```

I would like peerDependencies to also be able to match this. If you put the same in peerDependencies:

``` js
peerDependencies: {
  'ember-data': 'emberjs/data#beta'
}
```

It doesn't work because the real version is resolved by then.

It should be noted this is just for CI testing purposes, where I want to test all betas and canaries as new versions are released.

**Comment by isaacs** [comment]
So, you need to go from, eg, 1.2.3-beta to 1.2.4-beta?  In one range?

Ugh, that's some weird versioning, and kind of hard to do in a way that doesn't put us right back in the position that led to this restriction in the first place.  (That is, unexpectedly pulling prerelease code into production environments.)

The thing about peerDependencies not matching the github shorthand looks like a legit npm bug, but unrelated to node-semver.  This module doesn't know about those things, only versions and version ranges.

Would it be possible for ember-data to publish their prerelease versions with dist-tag set to `canary` or something?  It's as simple as them doing `npm publish --tag=canary` when they're publishing.  Then your program can do `"devDependencies": { "ember-data": "canary" }` and it'll work just fine.  That's a common way to handle this sort of thing.

**Comment by guybedford** [comment]
A `semver.maxSatisfyingUnstable` or similar could well be useful for opt-in to latest edge. I can send a PR if there is interest.

**Comment by isaacs** [comment]
As of version 5.6.0, you can do `semver.satisfies(version, range, { includePrerelease: true })` to include prerelease versions as if they weren't special.

(This option can also be passed to maxSatisfying, or when creating a range, etc.)

**Comment by aleclarson** [comment]
@isaacs Thank you for `includePrerelease`! Why does the following not work without it?
```js
semver.satisfies('2.0.0-beta.1', '*') // false
semver.satisfies('2.0.0-beta.1', '') // false
```
I thought `*` meant "any version allowed".
When that didn't work, I noticed this comment in the codebase:
https://github.com/npm/node-semver/blob/07244f913d0502d9400a88629710517ca9b7d702/semver.js#L1235
Yet empty string doesn't work either?

**Comment by isaacs** [comment]
> I thought * meant "any version allowed".

Any version other than a prerelease, yes :)

npm has some special handling of `*` when it's picking a manifest, to effectively do `includePrerelease` in that case.  https://github.com/npm/npm-pick-manifest/blob/latest/index.js#L79-L84
