### ISSUE TITLE
Incorrect Increment for versions < 1.0

### ISSUE THREAD

**Issue by tleunen** [npm/node-semver#177]
Given a version x.y.z, when x is 0, y should be incremented for a major version, and z for minor and patch. But the current version of semver treats a 0.x.y the same way as 1.x.y.

```
const semver = require("semver");
semver.inc('0.1.0', 'major');
```
gives 1.0.0 instead of 0.2.0

**Comment by brokenmass** [comment]
I don't agree.
how will you be able to move from a 0.x to 1.0 version then ?
and what would you expect `semver.major(0.2.0)` to return ?
I expect that `(semver.major(x) + 1) === semver.major(semver.inc(x, 'major'))`

it's your code that should take responsibility of handling the special 0.x case as the first number is always the identifier of major and the fact that semver allow to use, during version 0.x, bump in minor to handle breaking changes is irrelevant.
your code should be able to handle the logic and do something like (example of a semantic version bump):
```
if (semver.major(myVersion) === 0) {
  myNewVersion = semver.inc(myCurrentVersion, isBreakingChange(commit) ? 'minor' : 'patch');
} else {
  if(isBreakingChange(commit)) {
    myNewVersion = semver.inc('major');
  } else if (isNewFeature(commit)) {
    myNewVersion = semver.inc('minor');
  } else {
    myNewVersion = semver.inc('patch');
  }
}
```

**Comment by isaacs** [comment]
This is working as designed.  The technical term for the first number in the tuple is "major".

If you want to increment the minor version for a breaking change, then that's your call, and the semver specification is ambivalent about doing so in a 0.x version.  But the terms are still "major, minor, patch", regardless of whether the major version is 0.
