### ISSUE TITLE
Feature request: compare two ranges

### ISSUE THREAD

**Issue by ljharb** [npm/node-semver#178]
I'm trying to compare an existing semver range in a package.json, with a peerDependency range in another package.json - in other words, I want to see if the two ranges are compatible (ie, if there exists a version that satisfies both).

I tried playing with `Range` but couldn't come up with anything.

A simple example would be, `^1.2.3` and `<= 1.3.0` should return either a semver range that satisfies both, or the highest version number that satisfies both (either is sufficient).

Is this possible?

**Comment by platinumazure** [comment]
Seems like `maxSatisfying(versions, range)` would be really nice, if it allowed no versions and just generated the max possible range. But it could get unbounded pretty quickly on pathological input.

**Comment by shellscape** [comment]
came to the project today to request exactly this. we're presently using a litany of regular expressions (from some very old legacy code that I haven't gotten around to replacing) - https://github.com/gilt/gilt-swig-assets/blob/master/lib/swig-install/lib/merge-util.js#L73

**Comment by rtfpessoa** [comment]
+1
I was also looking into this, tried combining a couple of methods but I always end with false cases.

**Comment by rtfpessoa** [comment]
@ljharb @platinumazure @shellscape take a look in the PR I just made. It should be what you need.

**Comment by isaacs** [comment]
Landed in v5.4
