### ISSUE TITLE
Provide support for ASCII Strings

### ISSUE THREAD

**Issue by dev-dan** [npm/node-semver#194]
While I'm sure there is likely design reasons for it not doing so, I think it would be ideal to support ascii values. I spent an hour or so confused due to the following scenario:

I have a third party library that was returning a String with a value of `0.0.3`.
`semver.valid(value)` would return false, although it was expected to be true. 
`semver.gt(value, "0.0.2")` would produce an error, saying 0.0.3 is in invalid value. 

`typeof value` would return `string` and `value.valueOf` would return `0.0.3`. I could not figure out why a string with a value that's a simple semver would be invalid. After an hour or so, I realized the third party library was returning the string in ASCII, not UTF-8. Converting the string `0.0.3` to UTF allowed it to work with node-semver as expected. 

While the cause in this case was the third party libs choice to use ASCII, I feel like it would be ideal for node-semver to support those string types as well.

**Comment by isaacs** [comment]
When you say "ascii strings", I think perhaps you mean "String objects"?  Here's why.

There's no encoding difference between ascii and utf8 for the string "0.0.3" (or any valid semver) because ASCII is a subset of UTF-8.

Observe:

```
> s = '0.0.3'
'0.0.3'
> ascii = new Buffer(s, 'ascii')
<Buffer 30 2e 30 2e 33>
> utf8 = new Buffer(s, 'utf8')
<Buffer 30 2e 30 2e 33>
> ascii.toString('ascii') === utf8.toString('utf8')
true
> ascii.toString('utf8') === utf8.toString('ascii')
true
```

But also:

```
> semver.gt({toString: _ => '0.0.2'}, '0.0.3')
TypeError: Invalid Version: 0.0.2
    at new SemVer (/Users/isaacs/dev/js/semver/semver.js:293:11)
    at compare (/Users/isaacs/dev/js/semver/semver.js:580:10)
    at Function.gt (/Users/isaacs/dev/js/semver/semver.js:609:10)
    at repl:1:8
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:433:10)
    at emitOne (events.js:120:20)
> semver.gt(new String('0.0.3'), '0.0.2')
TypeError: Invalid Version: 0.0.3
    at new SemVer (/Users/isaacs/dev/js/semver/semver.js:293:11)
    at compare (/Users/isaacs/dev/js/semver/semver.js:580:10)
    at Function.gt (/Users/isaacs/dev/js/semver/semver.js:609:10)
    at repl:1:8
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:433:10)
    at emitOne (events.js:120:20)
```

The reason is because `typeof new String('0.0.2')` is `'object'`, not `'string'`.  That's what it's actually checking, the `typeof` of the argument.  If, as you say, the `typeof` of the thing you're passing in is `'string'`, then it wouldn't exhibit the behavior you're describing.

Assuming I'm interpreting the issue correctly, then the suggestion here is to coerce to string, rather than require that the thing be an actual string type.

It's not a terrible idea, but it is a bit of a concerning shift for a lib that's designed in part as a data validation utility.  If you want to coerce it to a string, I think you should do that in your application, by calling `semver.gt(firstVersion + '', secondVersion + '')` or `semver.gt(String(firstVersion), String(secondVersion))` explicitly.

**Comment by dev-dan** [comment]
I did state that typeof was string. That is exactly I found the issue so confusing. It is expected if the type is string, it will work, but it does not. 

`      var objOrString = thirdPartyLib.toAscii(updater.latestVer()]);
      console.log('objOrString is type ['+typeof objOrString + '] with value [' + objOrString + ']');
      if(semver.lt("0.0.2", web3.toAscii(updater.latestDApp()[0]))) { console.log("Science!"); }`

![image](https://cloud.githubusercontent.com/assets/7043191/26128560/6c7f4220-3a52-11e7-94bb-8ef24ddac446.png)

**Comment by isaacs** [comment]
I see.

Then the problem here is that the string isn't matching the SemVer regular expression.  Are those periods not actual `'.'` characters or something?

Can you provide me with a reproduction case?  Where are you getting the string from?

**Comment by isaacs** [comment]
Also, in your example, you're testing the `objOrString` variable, but then passing in `web3.toAscii(updater.latestDApp()[0])`, which could be a completely different thing.

**Comment by dev-dan** [comment]
As far as I can tell, the value is string everywhere and they are periods:
```
var objOrString = thirdPartyLib.toAscii(updater.latestDApp()[0]);
console.log('objOrString is type [' + typeof objOrString + '] with value [' + objOrString + ']');
console.log('thirdPartyLib.toAscii(updater.latest()) value type [' + typeof thirdPartyLib.toAscii(updater.latestDApp()[0]) + ']');
console.log('char is: ' +objOrString.charCodeAt(1) + ' expected '+ ".".charCodeAt(0));
if(semver.lt("0.0.2", web3.toAscii(updater.latestDApp()[0]))) { console.log("Science!"); }
```

![image](https://cloud.githubusercontent.com/assets/7043191/26132551/bcbbc844-3a66-11e7-87f5-607c25d7a1ff.png)

**Comment by dev-dan** [comment]
Again, to note -- converting the ascii string to utf8 allowed it to match.

**Comment by dev-dan** [comment]
Here is the code in thirdPartyLib.toAscii():
```
var toAscii = function(hex) {
    var str = "";
    var i = 0, l = hex.length;
    if (hex.substring(0, 2) === '0x') {
        i = 2;
    }
    for (; i < l; i+=2) {
        var code = parseInt(hex.substr(i, 2), 16);
        str += String.fromCharCode(code);
    }
    return str;
};
```
The value in updater.latest is `0x302e302e33000000000000000000000000000000000000000000000000000000`

**Comment by isaacs** [comment]
Oh, well you've got a bunch of null characters at the end of the string, that's the problem.

```js
var toAscii = function(hex) {
    var str = "";
    var i = 0, l = hex.length;
    if (hex.substring(0, 2) === '0x') {
        i = 2;
    }
    for (; i < l; i+=2) {
        var code = parseInt(hex.substr(i, 2), 16);
        str += String.fromCharCode(code);
    }
    return str;
};

var string = toAscii('0x302e302e33000000000000000000000000000000000000000000000000000000')

console.error('regexp match?', /^[0-9]+\.[0-9]+\.[0-9]+$/.test(string))
console.error('string=%j', string)
```

```
$ node ascii.js
regexp match? false
string="0.0.3\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
```

Strip those off.  `\u0000` characters aren't valid in a SemVer version string.

**Comment by dev-dan** [comment]
I see, thank you for clarifying this behavior for me.
