### ISSUE TITLE
satisfies() returns false when no minor version. intentional?

### ISSUE THREAD

**Issue by rally25rs** [npm/node-semver#198]
Just wanted to see if this is intentional behavior, or a bug. It seems that the `semver.satisfies()` function returns `false` if no minor version is specified:

```
$ node
> const s = require('semver')
undefined
> s.satisfies('6.3.0', '>6', false);
false
> s.satisfies('6.3.0', '>6.0', false);
true
```

semver version is 5.3.0

Thanks for any info!

**Comment by isaacs** [comment]
This is by design.

`>6` means "greater than any 6.x.x version", or in other words, `>=7.0.0`.

`>6.1` means "greater than any 6.1.x version", or in other words `>=6.2.0`

**Comment by rally25rs** [comment]
I think I'm answering my own question here, but someone please verify...

I'm guessing that this is because by this rule on https://docs.npmjs.com/misc/semver:

> 1 := 1.x.x := >=1.0.0 <2.0.0

so if `1` is equivelant to `>=1.0.0 <2.0.0` then `>1` has to be `> (>=1.0.0 <2.0.0)` which would be the same as `>=2.0.0`

**Comment by rally25rs** [comment]
Ah, you beat me to it by a second :) Thanks @isaacs

**Comment by isaacs** [comment]
@rally25rs Your folk explanation isn't quite how it works, but you landed on the right answer :)
