### ISSUE TITLE
Why are there so many ways to write a version range!?

### ISSUE THREAD

**Issue by danny-andrews** [npm/node-semver#203]
DISCLAIMER: I know you're not supposed to ask questions in GitHub issues, but here I am...

For example, for a range which accepts versions in the range `>=1.0.0 <2.0.0`, we have:
`^1.0.0`
`1 - 1`
`1.x`
`1.x.x`
`1.X`
`1.X.X`
`1.*`
`1.*.*`

Not only does this add a lot of complexity to this codebase, but there seems to be no standard way of writing these which adds a lot of cognitive load when scanning a `package.json` file.

Note, I like the `~`, `^`, `x`, and `-` range syntax. What I don't like are the `*`, `x`, and `X` aliases, as well as the one or two-digit shorthand notations. They just look wrong to when I'm looking through a `package.json`.

**Comment by isaacs** [comment]
https://twitter.com/horse_ebooks/status/228032106859749377

Sometimes things seemed like a good idea at the time, or worked by accident and became sort of standard, and in any case, it is what it is now.  I don't dispute the agony caused to you by the existence of these things.  But it is far less than the agony that would be caused to others by their removal.
