### ISSUE TITLE
Range match with a version that has a tag does not work

### ISSUE THREAD

**Issue by ixmatus** [npm/node-semver#207]
```shell
$ semver -r ">= 3.8.1" 3.9.1-1 || echo "does not match"
does not match
```

crypto-js@3.9.1-1 is breaking a build of mine because `node-semver` is not matching the version, despite the tag in the version.

Is this expected? Or should the tag be stripped? Any help is appreciated.

**Comment by isaacs** [comment]
Yes, this is by design.  Typically prerelease tags indicate that something is not yet ready for release, so they'll only match ranges that opt into matching a prerelease of that specific tuple.  See https://github.com/npm/node-semver#prerelease-tags

**Comment by ixmatus** [comment]
@isaacs okay thanks for explaining this and giving me documentation I can read!
