### ISSUE TITLE
Error parsing plugin /Users/username/.local/share/heroku/plugins/node_modules/semver

### ISSUE THREAD

**Issue by funkenstrahlen** [npm/node-semver#213]
I use `node v8.6.0` on macOS Sierra. When I run a command like `heroku` that uses node I get the following error:

```
 ▸    Error parsing plugin /Users/username/.local/share/heroku/plugins/node_modules/semver
 ▸    no commands found
```

The `semver` version installed is version `5.3.0`.

Any idea what's wrong?

**Comment by rvsheffer** [comment]
You need to change your directory to (cd) to /Users/username/.local/share/heroku/plugins/ and run npm install. This will ensure the latest semver library from npm is download. 

I am using node 8 and upgraded to macOS High Sierra and ran into this error.
