### ISSUE TITLE
Pre release version is ignored by semver.maxSatisfying

### ISSUE THREAD

**Issue by guptar8jan** [npm/node-semver#216]
I am using maxSatisfying method with following parameters:
const versions = [ '1.0.0',
  '1.0.1',
  '1.0.2',
  '1.0.3',
  '1.0.4',
  '1.1.2',
  '1.1.6',
  '1.1.7',
  '1.1.8',
  '1.1.9',
  '2.0.4',
  '2.1.7',
  '2.1.8-alpha.1' ]
semver.maxSatisfying(versions, '*', true)

RESULT: '2.1.7'

I am expecting '2.1.8-alpha.1'. 

I believe this is a bug. I traced to down to this line of code https://github.com/npm/node-semver/blob/master/semver.js#L1124. I believe replace CONTINUE, with 'return true' would makes sense. Please advice.

**Comment by isaacs** [comment]
Working as intended. https://github.com/npm/node-semver#prerelease-tags

Pre-release tags are strictly opt-in.
