### ISSUE TITLE
How to transform a one or two digit version into 3?

### ISSUE THREAD

**Issue by MartinMuzatko** [npm/node-semver#218]
Hey there! So far, we used two version numbers in our git history (0.1, 0.2, 0.3)
Is there a way to easily transform them into valid semver version strings?
The only question would be, what and where it is added. 
```
0.2 => 0.0.2
0.2 => 0.2.0
```
I would suggest to add it in front. 
Are there existing tools to do that?

**Comment by lomby92** [comment]
Easily with the new command **coerce**.

```javascript
const semver = require('semver')
let newVersion = semver.coerce('0.2') // return an object with some fields
console.log(newVersion.version) // print '0.2.0'
```

**Comment by MartinMuzatko** [comment]
Looks good  :) thank you

**Comment by Ruyven** [comment]
Is there a way to coerce it when it includes pre-release versions? E.g. 1.1-beta → 1.1.0-beta. `coerce` just changes it to `1.1.0` and cuts off the pre-release part.
