### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Haroenv** [npm/node-semver#220]
Hey, nice tool. I recently tried to upgrade, but wasn't sure what was going to change, so I had to read the commit history. It would be nice to have a changelog.md entry for this package. Thanks!

**Comment by trollepierre** [comment]
Hey guys,
9 months ago and no news from any changelog...

**Comment by yvele** [comment]
What's new in the [5.6.0](https://github.com/npm/node-semver/releases/tag/v5.6.0)?

**Comment by yvele** [comment]
A changelog would ne nice for such a massively deployed library 

![image](https://user-images.githubusercontent.com/4225430/46792256-3e81d880-cd43-11e8-9759-7a313547f243.png)
