### ISSUE TITLE
`intersects`: claims that `15` and `^16.0.0-0` intersect, but they should not

### ISSUE THREAD

**Issue by ljharb** [npm/node-semver#223]
(this necessitated [this workaround](https://github.com/airbnb/enzyme/pull/1404))

Basically, `semver.intersects('15', '^16.0.0-0')` returns `true`, and should return `false`. `semver.intersects('15', '^16.0.0')` properly returns `false`, and https://semver.npmjs.com/ for "react" and "^16.0.0-0"  properly does not include `15`.

I'm happy to submit a PR for this soon.

**Comment by isaacs** [comment]
This is definitely a bug.  My guess is it's related to using `semver.gt(v1, v2)` and friends (which don't exclude prereleases, since they're for comparison and sorting), where `semver.satisfies(v1, '>' + v2)` would be more appropriate.

**Comment by ljharb** [comment]
Thanks for the confirmation!

I started to work on a [branch](https://github.com/npm/node-semver/compare/master...ljharb:fix_intersects), which has two commits, one of which improves the tests and another which adds failing test cases. After in-person discussion with @zkat, I was told a fix is already in progress, so hopefully my commits can be helpful, whether cherry-picked in or simply used as suggestions.

**Comment by ljharb** [comment]
@zkat @iarna any update on this one? I can keep trying to work on my branch if that'd be helpful and nobody's still working on a fix.

**Comment by ljharb** [comment]
Glad this is finally fixed :-) unfortunately semver 7+ isn't an option for enzyme due to node support, so we'll have to keep the workaround for the foreseeable future :-/

**Comment by isaacs** [comment]
Yeah, not much chance of backporting to support EOL node versions, sorry.
