### ISSUE TITLE
Incrementing "1.0" does not work, returns undefined

### ISSUE THREAD

**Issue by hansemannn** [npm/node-semver#224]
Hey guys!

We noticed that when specifying a version like `1.0` instead of `1.0.0` to `semver -i` / `semver.inc()`, it does not increment it properly and returns undefined. Example:

```
$ semver 1.0.0 -i major
2.0.0
$ semver 1.0 -i major

```

Is there an option to bump it anyway or do we need to manually repair it? It feels overhead to do it but would of course be possible as well. Thank you!

**Comment by isaacs** [comment]
1.0 isn't a "version", it's a "range".  (That is, it's equivalent to `1.0.x`, and matches any non-prerelease versions from `1.0.0` up to but not including `1.1.0`.)

A better error message and non-zero exit code would be great, though.
