### ISSUE TITLE
diff should consider changes to 0.x.x versions to be major changes

### ISSUE THREAD

**Issue by iansu** [npm/node-semver#227]
Currently `diff` considers `0.1.0` to `0.2.0` to be a minor update. This might not be technically correct, as someone pointed out in an issue in yarn: https://github.com/yarnpkg/yarn/issues/4942

According to semver.org:
> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

**Comment by lomby92** [comment]
No, semver.org itself provide the definition:

> Semantic Versioning 2.0.0
> Summary
> 
> Given a version number MAJOR.MINOR.PATCH, increment the:
> 
>     MAJOR version when you make incompatible API changes,
>     MINOR version when you add functionality in a backwards-compatible manner, and
>     PATCH version when you make backwards-compatible bug fixes.
> 
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

**Comment by Enet4** [comment]
@lomby92 That would be deliberately ignoring the full specification. In fact, that quote is just the summary, which has no true weight on how we should interpret and implement the specification.

The statement regarding pre-1.0.0 versions precedes the one about major versions, and should take priority over those.

**Comment by isaacs** [comment]
The `semver.diff` method returns which portion of the semver tuple was changed.  It's not a normative explanation of whether it should be "considered" a breaking/additive/bugfix API change.  Current behavior is by design.
