### ISSUE TITLE
Coerce returns null if have a 0 appended to major, minor or patch

### ISSUE THREAD

**Issue by lomby92** [npm/node-semver#232]
Using **semver.coerce(<string>)** returns **null** value if there is one or more '0' before _major_, _minor_ or _patch_ value.
Some example of versions that fail:
- '0.02'
- '1.04'
- '0.67.09'
- '2018.06.05'

Maybe the coerce code can check also _major_, _minor_ and _path_ values as final step.

**Comment by lomby92** [comment]
@isaacs i have a fix for that, how can i push? Now i have permission denied

**Comment by bartvanandel** [comment]
The problem is not restricted to major, minor or patch value, it also fails with `2.0.0-20171117T112133.0734735.0`, i.e. a dot-separated part of the prerelease tag (which in our case is a git hash). It seems this problem only occurs when the part contains only numeric characters and starts with a zero (or zeroes). Adding a letter somewhere or removing the initial zeroes results in the expected result:

```
λ node
> const semver = require('semver')
undefined
> semver.valid('2.0.0-20171117T112133.0734735.0')
null
> semver.valid('2.0.0-20171117T112133.x734735.0')
'2.0.0-20171117T112133.x734735.0'
> semver.valid('2.0.0-20171117T112133.734735.0')
'2.0.0-20171117T112133.734735.0'
```

**Comment by bartvanandel** [comment]
@lomby92: if you create a fork of this repo and put your fix in a branch there, you can create a Pull Request from that branch :)

**Comment by andytompkins** [comment]
I just ran into this today. I was quite surprised that '1.123.000' was not considered valid, and that it would not coerce either. Sure, its redundant and silly that I have 000, but its actually outside of my control (I don't version the component that returns that.) It would be good if this could get fixed!

**Comment by yedlosh** [comment]
It's also then considerably misleading to say in readme that: 
"Only text which lacks digits will fail coercion"

**Comment by lukekarrys** [comment]
This can be done by using `loose: true` currently:

```
> semver.coerce('0000.004.02', { loose: true }).version
'0.4.2'
```
