### ISSUE TITLE
`intersects` returns true for some ranges that do not intersect

### ISSUE THREAD

**Issue by corhere** [npm/node-semver#239]
The `intersects` function can incorrectly return `true` when the first range has a comparator set with multiple comparators, and the second range has more than one comparator set (`a || b`).

```js
intersects('1.5.x', '<1.5.0')  // false
intersects('1.5.x', '>=1.6.0')  // false
intersects('1.5.x', '<1.5.0 || >=1.6.0')  // true?
intersects('<1.5.0 || >=1.6.0', '1.5.x')  // false
```

The flaw in the `intersects` algorithm is that it considers a set in the first range to intersect if every comparator in the set intersects with every comparator in **any** set in the second range. It needs to instead test whether there is some set in both ranges where all the comparators intersect.

**Comment by isaacs** [comment]
Fixed in version 6.0.0.  (It's a breaking change, even though it's a bugfix, because it could cause programs to need to be updated to keep working properly.)
