### ISSUE TITLE
semver.gt('1.2.3', '1.2.3-2') returns true

### ISSUE THREAD

**Issue by boldt** [npm/node-semver#242]
I am using `semver@5.5.0`. The following returns `false`:

```javascript
semver.gt('1.2.3-1', '1.2.3-2')
```

while the following returns `true`:

```javascript
semver.gt('1.2.3', '1.2.3-2')
```

I'm unsure, whether the second is correct? I would assume, that `1.2.3-2` is newer than `1.2.3`

**Comment by boldt** [comment]
Just read https://semver.org/ again:

> A pre-release version MAY be denoted by appending a hyphen

This means, that `1.2.3-1` is a prerelease of `1.2.3-2`, which itself is a prerelease of  `1.2.3`. Am I right?

**Comment by isaacs** [comment]
@boldt Yes, that is correct.  This is working as the spec indicates.  For what it's worth, I agree that this is a bit of a weird corner case in the specification, and can be confusing, but the time to usefully have that discussion is probably well past us now :)
