### ISSUE TITLE
Getting error parsing package json for semver

### ISSUE THREAD

**Issue by stanleyawang** [npm/node-semver#250]
while building the project through npm, am receiving this error occasionally 

![image](https://user-images.githubusercontent.com/15649572/43053624-48ac3002-8e60-11e8-84f2-1b06151d0335.png)

Some times rebuilding the whole project solves the issue, but some times it doesn't. Not sure what's the issue.

**Comment by isaacs** [comment]
What are you using to install modules?  (Ie, npm or yarn or something else, and what's the version.  If you're using npm, you can get this by running `npm -v`.)

This is not a problem with semver, but with whatever is putting semver onto your system.  Probably you can fix the issue by upgrading your package manager.

**Comment by stanleyawang** [comment]
@isaacs  thanks for your help! upgraded node version and its working fine now.
