### ISSUE TITLE
new feature isValid

### ISSUE THREAD

**Issue by dmytropanontko** [npm/node-semver#251]
Hey all, I currently try to use your module, and I need next func `semver.isValid(version)`.
And I have some other trouble. I tried handle your error throwing but have a problem with it. I can't catch it in `try, catch`. Code is follow:

```js
try {
    semver.valid(version)
  } catch (err) {
    throw 'Version must have correct format (example 10.25.0)'
  }
``` 

Thank you for attention

**Comment by isaacs** [comment]
You can just use `semver.valid()` as the test.  It doesn't throw when given an invalid version, it just returns `null`.  Otherwise, it strips out extraneous characters to provide a "clean" version.

```
> semver.valid('1.2.3')
'1.2.3'
> semver.valid('v1.2.3')
'1.2.3'
> semver.valid('woooo')
null
```

**Comment by isaacs** [comment]
So, to clarify, you can do `if (semver.valid(someString)) { ... }` if you need to test if a version is valid.

**Comment by dmytropanontko** [comment]
@isaacs when I did that I had TypeError which was uncontrolled. I can't catch this error and show my message. This is the reason why it's not so good to use thie method for validation. Thanks by answer

**Comment by dmytropanontko** [comment]
@isaacs 
Here code:
```js
try {
    // TODO: change this method if "semver" module will implement semver.isValid()
    semver.valid(version)
    console.log('1')
  } catch (err) {
    throw 'Version must have semver format (e.g. 10.25.0)'
  }
  console.log('2')
```

screenshot:
![image](https://user-images.githubusercontent.com/37536815/43158746-22bf4c1a-8f89-11e8-8550-14cb8f6fc68a.png)

**Comment by isaacs** [comment]
That's coming from elsewhere in the code.  Note that the `1` is being printed, so it's not throwing from the `semver.valid()` call you're quoting here.

It looks like botpress/src/util.js is calling semver.lt() with the version.  You should validate it before calling lt().

**Comment by dmytropanontko** [comment]
Thanks)
