### ISSUE TITLE
`semver.intersects` behaves inconsistently comparing range with prerelease version vs range

### ISSUE THREAD

**Issue by loganfsmyth** [npm/node-semver#254]
I know prerelease versions have a bit of edgecasey behavior, but I'm hoping to nail down if `false` is the unexpected result, or `true` is, or if this is just expected all around, given
```
semver.intersects(`<7.0.1`, "7.0.0-beta.0") // false - surprising?
semver.intersects(`<7.0.1`, "^7.0.0-beta.0") // true - expected
```

The inconsistency here is because [`.intersects` falls back to `.satisfies`](https://github.com/npm/node-semver/blob/acb44ddf2aef5855a1eb77fedc6b2e2c0868f7c8/semver.js#L728) when one of the arguments is an exact version, and `.satisfies` has [all this extra stuff](https://github.com/npm/node-semver/blob/acb44ddf2aef5855a1eb77fedc6b2e2c0868f7c8/semver.js#L1128) that doesn't apply when comparing a range with a range.

I can't tell if this is actually a bug in `.satisfies`, or what.

### Background

Babel is trying to use `semver` programmatically to decide when certain versions of things are available, and we ran into a little edge case. I _think_ we've worked around it for now with https://github.com/babel/babel/commit/13798feefbf19389cb692aa0b5157276ce7cdf4f#diff-7a78d3752af461cdbf66d58d59a2026dR169, but one thing I'd like verified, if possible, is whether this fix is actually safe. If the second (`true`-returning) example is actually incorrect, then a fix for it would cause serious regressions in behavior for Babel users, for instance.

**Comment by heyakyra** [comment]
Is this what is leading to these results: Using `elm` package on https://semver.npmjs.com/, `^0.19.1-0 || 0.19.0-no-deps` doesn't seem to match `0.19.1` (while `^0.19.0-0 || 0.19.0-no-deps` does seem to match `0.19.0`).

See: elm-community/elm-webpack-loader#183
