### ISSUE TITLE
maxSatisfying fails test case with ^0.0.0

### ISSUE THREAD

**Issue by Dru89** [npm/node-semver#259]
It seems like SemVer is failing to find a satisfying version in a case where I think it should be passing.

It's not able to find any matching version if your query is `^0.0.0`

### Expected:

```js
semver.maxSatisfying(['1.2.3', '1.2.4'], '^1.2.0')  // => 1.2.4
semver.maxSatisfying(['0.0.1', '0.0.2'], '^0.0')    // => 0.0.2
semver.maxSatisfying(['0.0.1', '0.0.2'], '^0.0.0')  // => 0.0.2
```

### Actual

```js
semver.maxSatisfying(['1.2.3', '1.2.4'], '^1.2.0')  // => 1.2.4
semver.maxSatisfying(['0.0.1', '0.0.2'], '^0.0')    // => 0.0.2
semver.maxSatisfying(['0.0.1', '0.0.2'], '^0.0.0')  // => null
```

**Comment by isaacs** [comment]
Working as designed.  https://github.com/npm/node-semver#caret-ranges-123-025-004

A caret range with a full version triplet of `0.0.n` will only match that specific version.  Thus, as the docs show, `^0.0.3` is equivalent to `>=0.0.3 <0.0.4`.  In the case of `^0.0.0`, that means, `>=0.0.0 <0.0.1`.

The reason why it works for `^0.0` is that the last item is unspecified.  Thus, `^0.0` is equivalent to `0.0.x`, ie, `>=0.0.0 <0.1.0`.
