### ISSUE TITLE
Why `parse` is not documented in README?

### ISSUE THREAD

**Issue by panlina** [npm/node-semver#269]
I never know about this function until I see it in an issue comment. Why not document it in README?

**Comment by jdmarshall** [comment]
Coworkers are pulling in an entirely different library (semver-utils) because they didn't know about semver.parse().

(use case: In CI environments you want the version number to match build numbers, and increment doesn't guarantee they are in lockstep.)

**Comment by isaacs** [comment]
9cb68f1db72d297183233f4d8d287e935f2b6ddd
