### ISSUE TITLE
`latest` as a range

### ISSUE THREAD

**Issue by hirokiosame** [npm/node-semver#272]
I'm not having any luck passing in `'latest'` as a range in `maxSatisfying`. It's looking to me like "latest" isn't regarded as a valid range.

Since npm supports `@latest`, can `latest` be supported in node-semver?

**Comment by isaacs** [comment]
Correct, `"latest"` is not a version range.  It is a dist-tag, which points to a specific version (not a range of versions).  npm looks at the `dist-tags` property on a package document in the registry, and that is how it knows which version to resolve to.

Perhaps what you want is the highest-precedent version in a set of versions?  In that case, you can do `semver.rsort(myArrayOfVersions)[0]`.
