### ISSUE TITLE
`semver.satisfies` returns true when given empty string, should throw error instead

### ISSUE THREAD

**Issue by caalberts** [npm/node-semver#279]
When given an empty string, `semver.satisfies(version, '')` is always true.

I think that this is misleading because it could lead to false positive effects where caller is dependent on the `true` result.

Throwing an error on invalid argument might be more appropriate here, as this is likely a programmer error.

**Comment by isaacs** [comment]
An empty string is a valid range.  It is equivalent to `*`.

It's not always true.  For example, prereleases don't match `*` unless you use the `includePrerelease` flag.

```
> require('semver').satisfies('1.2.3-beta', '')
false
> require('semver').satisfies('1.2.3-beta', '', {includePrerelease: true})
true
```

**Comment by euresch** [comment]
I also run into the same issue receiving true by calling semver.satisfies("1.0.0", "").  Then, reading the answer, that an empty string is equivalent to `*` I tried out semver.satisfies("1.0.0", "*") and the result is true as well. So, it seems strange to me, why an empty string is implicitly handled as `*`?
