### ISSUE TITLE
command-line version does not correctly parse ^ versions

### ISSUE THREAD

**Issue by ducttapecoder-vt** [npm/node-semver#280]
When using https://semver.npmjs.com/ with @ng-idle/keepalive and ^6.0.0-beta.3, versions 6.0.0-beta.3, 6.0.0-beta.4, and 6.0.0-beta.5 are returned. However node-semver does not do the same.

> semver '2.0.0-beta.1' '2.0.0-beta.2' '2.0.0-beta.3' '2.0.0-beta.4' '2.0.0-beta.5' '2.0.0-beta.6' '2.0.0-beta.7' '2.0.0-beta.8' '2.0.0-beta.9' '2.0.0-beta.10' '2.0.0-beta.11' '2.0.0-beta.12' '2.0.0-beta.13' '2.0.0-beta.15' '6.0.0-beta.1' '6.0.0-beta.2' '6.0.0-beta.3' '6.0.0-beta.4' '6.0.0-beta.5' '7.0.0-beta.1' -r "^6.0.0-beta.3"
**> 6.0.0-beta.3**

Adding -p does not change the behavior.

I've tried other packages as well and it doesn't seem to grab the alternate versions:

> semver -r ^7.0.2 4.0.0 4.0.0-rc.0 4.0.0-rc.1 4.0.0-rc.2 4.0.0-rc.3 4.0.0-rc.4 4.0.0-rc.5 4.0.0-rc.6 4.0.1 4.0.2 4.0.3 4.1.0 4.1.0-beta.0 4.1.0-beta.1 4.1.0-rc.0 4.1.1 4.1.2 4.1.3 4.2.0 4.2.0-beta.0 4.2.0-beta.1 4.2.0-rc.0 4.2.0-rc.1 4.2.0-rc.2 4.2.1 4.2.2 4.2.3 4.2.4 4.2.5 4.2.6 4.3.0 4.3.0-beta.0 4.3.0-beta.1 4.3.0-rc.0 4.3.1 4.3.2 4.3.3 4.3.4 4.3.5 4.3.6 4.4.0-RC.0 4.4.1 4.4.2 4.4.3 4.4.4 4.4.5 4.4.6 4.4.7 5.0.0 5.0.0-beta.0 5.0.0-beta.1 5.0.0-beta.2 5.0.0-beta.3 5.0.0-beta.4 5.0.0-beta.5 5.0.0-beta.6 5.0.0-beta.7 5.0.0-rc.0 5.0.0-rc.1 5.0.0-rc.2 5.0.0-rc.35.0.0-rc.4 5.0.0-rc.5 5.0.0-rc.6 5.0.0-rc.7 5.0.0-rc.8 5.0.0-rc.9 5.0.1 5.0.2 5.0.3 5.0.4 5.0.5 5.1.0 5.1.0-beta.0 5.1.0-beta.1 5.1.0-beta.2 5.1.0-rc.0 5.1.0-rc.1 5.1.1 5.1.2 5.1.3 5.2.0 5.2.0-beta.0 5.2.0-beta.1 5.2.0-rc.0 5.2.1 5.2.10 5.2.11 5.2.2 5.2.3 5.2.4 5.2.5 5.2.6 5.2.7 5.2.8 5.2.9 6.0.0 6.0.0-beta.0 6.0.0-beta.1 6.0.0-beta.2 6.0.0-beta.3 6.0.0-beta.4 6.0.0-beta.5 6.0.0-beta.6 6.0.0-beta.7 6.0.0-beta.8 6.0.0-rc.0 6.0.0-rc.1 6.0.0-rc.2 6.0.0-rc.3 6.0.0-rc.4 6.0.0-rc.5 6.0.0-rc.6 6.0.1 6.0.2 6.0.3 6.0.4 6.0.5 6.0.6 6.0.7 6.0.8 6.0.9 6.1.0 6.1.0-beta.0 6.1.0-beta.1 6.1.0-beta.2 6.1.0-beta.3 6.1.0-rc.0 6.1.0-rc.3 6.1.1 6.1.10 6.1.2 6.1.3 6.1.4 6.1.6 6.1.7 6.1.8 6.1.9 7.0.0 7.0.0-beta.0 7.0.0-beta.1 7.0.0-beta.2 7.0.0-beta.3 7.0.0-beta.4 7.0.0-beta.5 7.0.0-beta.6 7.0.0-beta.7 7.0.0-rc.0 7.0.0-rc.1 7.0.1 7.0.2 7.0.3 7.0.4 7.1.0 7.1.0-beta.0 7.1.0-beta.1 7.1.0-beta.2 7.1.0-rc.0 7.1.1 7.1.2 7.1.3 7.1.4 7.2.0 7.2.0-beta.0 7.2.0-beta.1 7.2.0-beta.2 7.2.0-rc.0 7.2.1 7.2.10 7.2.11 7.2.12 7.2.13 7.2.14 7.2.15 7.2.2 7.2.3 7.2.4 7.2.5 7.2.6 7.2.7 7.2.8 7.2.9 8.0.0 8.0.0-beta.0 8.0.0-beta.1 8.0.0-beta.10 8.0.0-beta.11 8.0.0-beta.12 8.0.0-beta.13 8.0.0-beta.14 8.0.0-beta.2 8.0.0-beta.3 8.0.0-beta.4 8.0.0-beta.5 8.0.0-beta.6 8.0.0-beta.7 8.0.0-beta.8 8.0.0-beta.9 8.0.0-rc.0 8.0.0-rc.1 8.0.0-rc.2 8.0.0-rc.3 8.0.0-rc.4 8.0.0-rc.5 8.0.1 8.1.0-beta.0 8.1.0-next.1 8.1.0-next.2
**> 7.0.2**

With ~ it seems to work correctly:

> PS C:\Users\User\Documents>semver 1.0.0 1.0.1 1.0.2 1.0.2-beta.1 1.0.3 -r ~1.0.1
> 1.0.1
> 1.0.2
> 1.0.3
> PS C:\Users\User\Documents> semver 1.0.0 1.0.1 1.0.2 1.0.2-beta.1 1.0.3 -r ~1.0.1 -p
> 1.0.1
> 1.0.2-beta.1
> 1.0.2
> 1.0.3

And then you get this:

> PS C:\Users\User\Documents> semver 1.0.0 1.0.1 1.0.2 1.0.2-beta.1 1.0.3 -r ^1.0.1
> 1.0.1

Edit: Sorry for all the edits. Figured out that ~ works correctly but ^ does not match the documented behavior.

**Comment by isaacs** [comment]
This seems to work fine for me.  `^` is a special character on the Windows command line, perhaps try wrapping in quotes?

**Comment by ducttapecoder-vt** [comment]
You can see in my very first entry that I wrapped the items in single
quotes. Can you give me an example of a successful test?

**Comment by isaacs** [comment]
Here's what I get:

```
$ semver '2.0.0-beta.1' '2.0.0-beta.2' '2.0.0-beta.3' '2.0.0-beta.4' '2.0.0-beta.5' '2.0.0-beta.6' '2.0.0-beta.7' '2.0.0-beta.8' '2.0.0-beta.9' '2.0.0-beta.10' '2.0.0-beta.11' '2.0.0-beta.12' '2.0.0-beta.13' '2.0.0-beta.15' '6.0.0-beta.1' '6.0.0-beta.2' '6.0.0-beta.3' '6.0.0-beta.4' '6.0.0-beta.5' '7.0.0-beta.1' -r "^6.0.0-beta.3"
6.0.0-beta.3
6.0.0-beta.4
6.0.0-beta.5
```

When you  run `semver` with no arguments, it'll print out the version of semver.  What do you get when you  do that?

**Comment by ducttapecoder-vt** [comment]
It was 6.1.1 when I submitted, I've upgraded to 6.1.2 and retried. Powershell doesn't seem to care how you encapsulate the data, even as a variable, as long as you break it out. I notice however in command prompt that it cares whether you use single or double quotes (no response vs correct response).

Given that I'm trying to write a powershell script based on the output, this is very unfortunate behavior, but it's also behavior I've never seen out of Powershell before. When you wrap a string with single quotes, it takes the text as a literal and does not interpret it so it should not be doing anything with the ^. ^ is not a special character in Powershell either.

**CMD:**

> C:\Users\user>semver '2.0.0-beta.1' '2.0.0-beta.2' '2.0.0-beta.3' '2.0.0-beta.4' '2.0.0-beta.5' '2.0.0-beta.6' '2.0.0-beta.7' '2.0.0-beta.8' '2.0.0-beta.9' '2.0.0-beta.10' '2.0.0-beta.11' '2.0.0-beta.12' '2.0.0-beta.13' '2.0.0-beta.15' '6.0.0-beta.1' '6.0.0-beta.2' '6.0.0-beta.3' '6.0.0-beta.4' '6.0.0-beta.5' '7.0.0-beta.1' -r "^6.0.0-beta.3"
> (no response)
> C:\Users\user>semver
> SemVer 6.1.2

> C:\Users\user>semver "2.0.0-beta.1" "2.0.0-beta.2" "2.0.0-beta.3" "2.0.0-beta.4" "2.0.0-beta.5" "2.0.0-beta.6" "2.0.0-beta.7" "2.0.0-beta.8" "2.0.0-beta.9" "2.0.0-beta.10" "2.0.0-beta.11" "2.0.0-beta.12" "2.0.0-beta.13" "2.0.0-beta.15" "6.0.0-beta.1" "6.0.0-beta.2" "6.0.0-beta.3" "6.0.0-beta.4" "6.0.0-beta.5" "7.0.0-beta.1" -r "^6.0.0-beta.3"
> 6.0.0-beta.3
> 6.0.0-beta.4
> 6.0.0-beta.5

**Powershell:**
single-double
> PS C:\Users\user> semver '2.0.0-beta.1' '2.0.0-beta.2' '2.0.0-beta.3' '2.0.0-beta.4' '2.0.0-beta.5' '2.0.0-beta.6' '2.0.0-beta.7' '2.0.0-beta.8' '2.0.0-beta.9' '2.0.0-beta.10' '2.0.0-beta.11' '2.0.0-beta.12' '2.0.0-beta.13' '2.0.0-beta.15' '6.0.0-beta.1' '6.0.0-beta.2' '6.0.0-beta.3' '6.0.0-beta.4' '6.0.0-beta.5' '7.0.0-beta.1' -r "^6.0.0-beta.3"
> 6.0.0-beta.3

double-double

> PS C:\Users\user> semver "2.0.0-beta.1" "2.0.0-beta.2" "2.0.0-beta.3" "2.0.0-beta.4" "2.0.0-beta.5" "2.0.0-beta.6" "2.0.0-beta.7" "2.0.0-beta.8" "2.0.0-beta.9" "2.0.0-beta.10" "2.0.0-beta.11" "2.0.0-beta.12" "2.0.0-beta.13" "2.0.0-beta.15" "6.0.0-beta.1" "6.0.0-beta.2" "6.0.0-beta.3" "6.0.0-beta.4" "6.0.0-beta.5" "7.0.0-beta.1" -r "^6.0.0-beta.3"
> 6.0.0-beta.3

double-single

> PS C:\Users\user> semver "2.0.0-beta.1" "2.0.0-beta.2" "2.0.0-beta.3" "2.0.0-beta.4" "2.0.0-beta.5" "2.0.0-beta.6" "2.0.0-beta.7" "2.0.0-beta.8" "2.0.0-beta.9" "2.0.0-beta.10" "2.0.0-beta.11" "2.0.0-beta.12" "2.0.0-beta.13" "2.0.0-beta.15" "6.0.0-beta.1" "6.0.0-beta.2" "6.0.0-beta.3" "6.0.0-beta.4" "6.0.0-beta.5" "7.0.0-beta.1" -r '^6.0.0-beta.3'
> 6.0.0-beta.3

double-single with '-r' encapsulated
> PS C:\Users\user> semver "2.0.0-beta.1" "2.0.0-beta.2" "2.0.0-beta.3" "2.0.0-beta.4" "2.0.0-beta.5" "2.0.0-beta.6" "2.0.0-beta.7" "2.0.0-beta.8" "2.0.0-beta.9" "2.0.0-beta.10" "2.0.0-beta.11" "2.0.0-beta.12" "2.0.0-beta.13" "2.0.0-beta.15" "6.0.0-beta.1" "6.0.0-beta.2" "6.0.0-beta.3" "6.0.0-beta.4" "6.0.0-beta.5" "7.0.0-beta.1" '-r' '^6.0.0-beta.3'
> 6.0.0-beta.3

single-single
> PS C:\Users\user> semver '2.0.0-beta.1' '2.0.0-beta.2' '2.0.0-beta.3' '2.0.0-beta.4' '2.0.0-beta.5' '2.0.0-beta.6' '2.0.0-beta.7' '2.0.0-beta.8' '2.0.0-beta.9' '2.0.0-beta.10' '2.0.0-beta.11' '2.0.0-beta.12' '2.0.0-beta.13' '2.0.0-beta.15' '6.0.0-beta.1' '6.0.0-beta.2' '6.0.0-beta.3' '6.0.0-beta.4' '6.0.0-beta.5' '7.0.0-beta.1' -r '^6.0.0-beta.3'
> 6.0.0-beta.3

single-single with '-r' encapsulated
> PS C:\Users\user> semver '2.0.0-beta.1' '2.0.0-beta.2' '2.0.0-beta.3' '2.0.0-beta.4' '2.0.0-beta.5' '2.0.0-beta.6' '2.0.0-beta.7' '2.0.0-beta.8' '2.0.0-beta.9' '2.0.0-beta.10' '2.0.0-beta.11' '2.0.0-beta.12' '2.0.0-beta.13' '2.0.0-beta.15' '6.0.0-beta.1' '6.0.0-beta.2' '6.0.0-beta.3' '6.0.0-beta.4' '6.0.0-beta.5' '7.0.0-beta.1' '-r' '^6.0.0-beta.3'
> 6.0.0-beta.3

As a big block:

> PS C:\Users\user> semver "2.0.0-beta.1 2.0.0-beta.2 2.0.0-beta.3 2.0.0-beta.4 2.0.0-beta.5 2.0.0-beta.6 2.0.0-beta.7 2.0.0-beta.8 2.0.0-beta.9 2.0.0-beta.10 2.0.0-beta.11 2.0.0-beta.12 2.0.0-beta.13 2.0.0-beta.15 6.0.0-beta.1 6.0.0-beta.2 6.0.0-beta.3 6.0.0-beta.4 6.0.0-beta.5 7.0.0-beta.1" -r "^6.0.0-beta.3"
> (no response)

As a Variable:

> PS C:\Users\user> $val = "^6.0.0-beta.3"
> PS C:\Users\user> $val
> ^6.0.0-beta.3
> PS C:\Users\user> semver '2.0.0-beta.1' '2.0.0-beta.2' '2.0.0-beta.3' '2.0.0-beta.4' '2.0.0-beta.5' '2.0.0-beta.6' '2.0.0-beta.7' '2.0.0-beta.8' '2.0.0-beta.9' '2.0.0-beta.10' '2.0.0-beta.11' '2.0.0-beta.12' '2.0.0-beta.13' '2.0.0-beta.15' '6.0.0-beta.1' '6.0.0-beta.2' '6.0.0-beta.3' '6.0.0-beta.4' '6.0.0-beta.5' '7.0.0-beta.1' -r $val
> 6.0.0-beta.3

**Comment by isaacs** [comment]
Yeah, I don't know what to tell you, sorry.  I left Windows as my primary environment long before Powershell was invented, and I've been all-in on Bash ever since.  It looks like semver is trying to do the right thing.  You could add a `console.error(process.argv)` just to see what it's getting passed into it in different situations?  /shrug
