### ISSUE TITLE
^0.0.4 range does not match 0.0.5 and above

### ISSUE THREAD

**Issue by marechal-p** [npm/node-semver#281]
Since I am playing with versions in the 0.0.x range, it may also be by design, but still surprising.

Is it intended this way? I can still emulate the desired behavior, just looks weird:

```node
> satisfies('0.0.5', '^0.0.4')
false // ko
> satisfies('0.1.5', '^0.1.4')
true // ok
> satisfies('0.0.4', '>= 0.0.4 < 0.1')
true // what I wanted
```

**Comment by isaacs** [comment]
Yes, that is by design.  `^` means "no known breaking changes".  In practice, this means locking down the first non-zero version number in the tuple.  So, `^1.2.3` is `1.x >=1.2.3`.  `^0.2.3` is `0.2.x >=0.2.3`.  `^0.0.3` just... well, `0.0.3`.

**Comment by marechal-p** [comment]
Thank you for the insight! I could not find this written elsewhere, or maybe I did not understand then.

**Comment by alasdairhurst** [comment]
@isaacs if this is by design, then can you explain the following?
```
> satisfies('0.0.5', '^0.0.4')
false
> satisfies('0.0.5', '~0.0.4')
false
```

Surely ~ is supposed to be _more_ restrictive than ^ in most cases?

**Comment by ljharb** [comment]
@alasdairhurst nope, not for versions under v1, which is exactly why the ecosystem added and moved to use ^.
