### ISSUE TITLE
Weird version range behavior when using includePrerelease: true

### ISSUE THREAD

**Issue by mxlle** [npm/node-semver#282]
I want to define a version range that matches all versions of a certain major, including any prereleases of this major. 

I tried using just "2" or "2.x.x" and adding the `includePrerelease: true` option to all function calls, however then I get weird behavior at the corner cases: 

```
semver.satisfies("2.0.0-pre.0", "2.x.x", {includePrerelease: true}); // false, I expected true
semver.satisfies("2.1.0-pre.0", "2.x.x", {includePrerelease: true}); // true
semver.satisfies("3.0.0-pre.0", "2.x.x", {includePrerelease: true}); // true, I expected false
```
I know that this behavior matches the definition of `^1.x := >=1.0.0 <2.0.0`
However I think the behavior should be altered in case of the `includePrerelease` flag. 

It's relevant for the following situation: 
- I implement a program against the interface of version 2.x.x. 
- I want to always get the newest version of this interface, also prereleases, so I use the includePrerelease flag. 
- However as soon as there is an 3.0.0-pre, **this will break my interface** because it's treated as 2.x.x

**Comment by isaacs** [comment]
Ah, yeah.  That is a legit bug, completely violates the expectation.  `1.x` should probably be `>=1.0.0-0 <2.0.0-0` if `includePrereleases` is set.

**Comment by isaacs** [comment]
Fixed in 6.1.3.  Thanks for the report!

**Comment by mxlle** [comment]
Thank you for fixing the issue this quickly! Now I get the expected result :+1:

**Comment by sarnesjo** [comment]
The behavior of `~` and `^` now appears to be inconsistent; do they need to be updated as well?

See, for example, the "unlocked prerelease range tests" test.

**Comment by mbargiel** [comment]
Indeed, I'm running into the same issue with `^`  and `~`. 

Using `node-semver@6.3.0` I'm seeing the following inconsistency with `~`:
```
> semver.satisfies('1.0.1-beta', '~1.0.0', { includePrerelease: true })
true
> semver.satisfies('1.1.0-beta', '~1.0.0', { includePrerelease: true })
true # expected false!
> semver.satisfies('2.0.0-beta', '~1.0.0', { includePrerelease: true })
false
```
and with `^`:
```
> semver.satisfies('1.0.1-beta', '^1.0.0', { includePrerelease: true })
true
> semver.satisfies('1.1.0-beta', '^1.0.0', { includePrerelease: true })
true
> semver.satisfies('2.0.0-beta', '^1.0.0', { includePrerelease: true })
true # expected false!
```
Straight out `>=` seems fine however.
```
> semver.satisfies('1.0.1-beta', '>=1.0.0', { includePrerelease: true })
true
> semver.satisfies('1.1.0-beta', '>=1.0.0', { includePrerelease: true })
true
> semver.satisfies('2.0.0-beta', '>=1.0.0', { includePrerelease: true })
true
```
Should I reopen this ticket or open a new one?

**Comment by mbargiel** [comment]
A workaround is to manually unwrap the `^`  and `~`, e.g. 
```
> semver.satisfies('1.1.0-beta', '>=1.0.0 <1.1.0-0', { includePrerelease: true })
false # as expected
```
