### ISSUE TITLE
special cases in dependency ranges

### ISSUE THREAD

**Issue by lcwj3** [npm/node-semver#285]
I am working on parsing the dependency ranges and we have found a lot of special cases for ranges, like github/gitlab urls, local file urls, also some strange strings which looks like a tag in dist-tags(like alpha,beta, feature_all, etc), but actually they are not tags. I have tried this tool but it seems can not handle these,,, Is there any solution on parsing such cases?

**Comment by isaacs** [comment]
Perhaps you're looking for something like https://github.com/npm/npm-package-arg?

**Comment by lcwj3** [comment]
> Perhaps you're looking for something like https://github.com/npm/npm-package-arg?

Thanks for your reply, this can help me, but actually I am trying to parse the dependency range, it is sort of combination of node-semver and npm-package-arg, because when installing a library A, we use npm install A@1.1.0, then install the dependencies recursively, I am wondering if there is a tool which can handle all dependency ranges (including semantic version range and tags and urls), if not, I can also try to combine these two tools, thanks!

**Comment by lcwj3** [comment]
I have tried this npm-package-arg, it has the classification on different dep types, I misunderstand that before, this do help me a lot, thanks and will close this issue right now.

**Comment by isaacs** [comment]
Glad I could help :)
