### ISSUE TITLE
[FEATURE] Separate functions into isolated imports for tree shaking

### ISSUE THREAD

**Issue by Aghassi** [npm/node-semver#291]
# What / Why
We rely on two or three functions out of this package, and it costs us 5kbs minified at runtime in the browser. We would like the ability to treeshake modules such that we can continue to rely on the package.

Here is the bundlephobia for the package currently. https://bundlephobia.com/result?p=semver@6.3.0

## Where
Enterprise products owned by Intuit

## How
Instead of doing

```js
import semver from "semver"

// ...

semver.valid(/* ... */);
```

Have the ability to do

```js
import valid from "semver/valid"

valid();
```

### Current Behavior
I must import the entire default module to ensure that I can get a single function off of the module.

### Expected Behavior
I should be able to import only the functionality that I care about when targeting the web.

## Who
@aghassi

## References
* n/a

Although there are similar alternatives for specific use cases such as https://www.npmjs.com/package/semver-compare

**Comment by isaacs** [comment]
Sounds good to me.  Patch welcome.

**Comment by isaacs** [comment]
Note: this would actually be good for npm as well, since it doesn't use most of the features that this module has grown over the years.
