### ISSUE TITLE
[FEATURE] Object or interface Semver

### ISSUE THREAD

**Issue by mehdihaddad** [npm/node-semver#292]
# What / Why
Maybe it's better to have an semver object on angular.
For exemple :
`import { Semver } from 'semver';`
`...`
`Semver.compare(a, b); `

And you have the doc and everything for completion on VSCode for exemple.
Now, `semver = require('semver');` is a simple any and you have to write correctly the functions and parameters.

**Comment by isaacs** [comment]
You can do that right now.  `const {SemVer} = require('semver')` or `import {SemVer} from 'semver'` both work to get the SemVer class.
