### ISSUE TITLE
[QUESTION] Confusing parsing of beta versions

### ISSUE THREAD

**Issue by rarkins** [npm/node-semver#297]
# What / Why

`semver.compare('0.0.1-beta.3clear', '0.0.1-beta.4')` returns `1`. Reference: https://runkit.com/rarkins/5dd81379965bd6001c3f184d

Yet if I test on semver.npmjs.com, it matches my expectations:

![image](https://user-images.githubusercontent.com/6311784/69444029-d1b37d00-0d4f-11ea-9b20-4f6d3b228e08.png)

Same with npm CLI:
```
❯ npm outdated
Package                  Current        Wanted         Latest  Location
eslint-plugin-rxjs  0.0.1-beta.5  0.0.1-beta.5  0.0.1-beta.10  global
```

The `semver.compare` result seems wrong, but I wonder if I am missing something.

## Where

* n/a

## Who

* n/a

## References

* n/a

**Comment by isaacs** [comment]
The reason is that `3clear` is a non-numeric identifier, because it includes non-numeric characters ("clear").

```
> semver.compare('0.0.1-beta.3clear', '0.0.1-beta.4')
1
> semver.compare('0.0.1-beta.3.clear', '0.0.1-beta.4')
-1
```

The semver spec says in [section 11](https://semver.org/#spec-item-11):

> Precedence for two pre-release versions with the same major, minor, and patch version MUST be determined by comparing each dot separated identifier from left to right until a difference is found as follows: identifiers consisting of **only** digits are compared numerically and identifiers **with letters or hyphens** are compared lexically in ASCII sort order. **Numeric identifiers always have lower precedence than non-numeric identifiers.**

So, this is working as intended.

**Comment by rassie** [comment]
@isaacs this does not explain the result on semver.npmjs.com. Is there a bug there, doesn't it use `node-semver`?

**Comment by rarkins** [comment]
@isaacs what I was trying to convey is that it appears to be behaving in different ways depending on where I try it. If I try to emulate the same comparison using npm cli, `0.0.1-beta.3clear` comes before `0.0.1-beta.4`. And similarly if I use your semver.npmjs.com web interface, it does not show 3clear being highest.

So it seems `semver.compare` is correct in its implementation, but is `npm` using it a different way somehow, or did I manage to misunderstand both the examples I gave above?

**Comment by rarkins** [comment]
FWIW I don't dispute the semver behaviour, but I'm keen to understand why npm cli's and semver.npmjs.com's behavior appears to be different.

On semver.npmjs.com it appears to be sorting "alphanumerically" on load (`3clear` comes after `2` and before `4`), but then it's impossible to capture it in either a less than or greater than expression:

![image](https://user-images.githubusercontent.com/6311784/69501364-77a7e880-0f04-11ea-947f-b0e46191d2cb.png)
![image](https://user-images.githubusercontent.com/6311784/69501369-8098ba00-0f04-11ea-9d4f-afd38a96759c.png)

**Comment by rarkins** [comment]
`npm` CLI does indeed use this package: https://github.com/npm/cli/blob/b829d62c98506325d2afb2d85d191a8ff1c49157/package.json#L130

So the question is why npm's behavior is different to `node-semver`'s default behavior. One could even argue that `npm`'s behavior is non-compliant?

**Comment by isaacs** [comment]
This looks like a bug in semver.npmjs.com (or maybe using an outdated version of node-semver).

Here's what I get from using the module directly: https://gist.github.com/isaacs/df9a100dac9ed0784fb9e746a2cc16cc

**Comment by isaacs** [comment]
Oh, no, spoke too soon.

The discrepancy is in using the `loose` option (which the CLI does in most cases, so that it can still install packages created prior to the SemVer v2 spec's existence).  It looks like semver.npmjs.com is also using loose mode.

Updated the gist to demo the loose param as well.

**Comment by isaacs** [comment]
It looks like npm is doing the right thing, too:

```
$ npm view eslint-plugin-rxjs@'>0.0.1-beta.5' version
eslint-plugin-rxjs@0.0.1-beta.3clear '0.0.1-beta.3clear'
eslint-plugin-rxjs@0.0.1-beta.6 '0.0.1-beta.6'
eslint-plugin-rxjs@0.0.1-beta.7 '0.0.1-beta.7'
eslint-plugin-rxjs@0.0.1-beta.8 '0.0.1-beta.8'
eslint-plugin-rxjs@0.0.1-beta.10 '0.0.1-beta.10'

$ npm view eslint-plugin-rxjs@'<=0.0.1-beta.3clear' version
eslint-plugin-rxjs@0.0.1-beta.0 '0.0.1-beta.0'
eslint-plugin-rxjs@0.0.1-beta.1 '0.0.1-beta.1'
eslint-plugin-rxjs@0.0.1-beta.2 '0.0.1-beta.2'
eslint-plugin-rxjs@0.0.1-beta.3clear '0.0.1-beta.3clear'
eslint-plugin-rxjs@0.0.1-beta.4 '0.0.1-beta.4'
eslint-plugin-rxjs@0.0.1-beta.5 '0.0.1-beta.5'
eslint-plugin-rxjs@0.0.1-beta.6 '0.0.1-beta.6'
eslint-plugin-rxjs@0.0.1-beta.7 '0.0.1-beta.7'
eslint-plugin-rxjs@0.0.1-beta.8 '0.0.1-beta.8'
eslint-plugin-rxjs@0.0.1-beta.10 '0.0.1-beta.10'

$ npm view eslint-plugin-rxjs@'<0.0.1-beta.3clear' version
eslint-plugin-rxjs@0.0.1-beta.0 '0.0.1-beta.0'
eslint-plugin-rxjs@0.0.1-beta.1 '0.0.1-beta.1'
eslint-plugin-rxjs@0.0.1-beta.2 '0.0.1-beta.2'
eslint-plugin-rxjs@0.0.1-beta.4 '0.0.1-beta.4'
eslint-plugin-rxjs@0.0.1-beta.5 '0.0.1-beta.5'
eslint-plugin-rxjs@0.0.1-beta.6 '0.0.1-beta.6'
eslint-plugin-rxjs@0.0.1-beta.7 '0.0.1-beta.7'
eslint-plugin-rxjs@0.0.1-beta.8 '0.0.1-beta.8'
eslint-plugin-rxjs@0.0.1-beta.10 '0.0.1-beta.10'

$ npm view eslint-plugin-rxjs@'<=0.0.1-beta.2' version
eslint-plugin-rxjs@0.0.1-beta.0 '0.0.1-beta.0'
eslint-plugin-rxjs@0.0.1-beta.1 '0.0.1-beta.1'
eslint-plugin-rxjs@0.0.1-beta.2 '0.0.1-beta.2'

$ npm view eslint-plugin-rxjs@'>0.0.1-beta.2' version
eslint-plugin-rxjs@0.0.1-beta.3clear '0.0.1-beta.3clear'
eslint-plugin-rxjs@0.0.1-beta.4 '0.0.1-beta.4'
eslint-plugin-rxjs@0.0.1-beta.5 '0.0.1-beta.5'
eslint-plugin-rxjs@0.0.1-beta.6 '0.0.1-beta.6'
eslint-plugin-rxjs@0.0.1-beta.7 '0.0.1-beta.7'
eslint-plugin-rxjs@0.0.1-beta.8 '0.0.1-beta.8'
eslint-plugin-rxjs@0.0.1-beta.10 '0.0.1-beta.10'
```

So yeah, bug in semver.npmjs.com, maybe?  I'll look into what version semver it's using.

What version of npm are you using that's hot behaving the same way?  `npm -v` will tell you.

**Comment by rarkins** [comment]
@isaacs thanks for looking into it. I think there's maybe another explanation. Let me know what you think?

Q: why is semver.npmjs.com sorting correctly?
A: it's not sorting at all! that ordering is just reflecting the order they were published to the registry.

Q: why does the 3clear version not satisfy either range?
A: because the code not only tests against the range but also enforces a max matching version of `latest`: https://github.com/npm/semver.npmjs.com/blob/6a29619986430438e0f629011e5d2345b47dea88/src/entry.js#L30-L38

Q: why does npm cli not suggest 3clear as an upgrade option?
A: same reason as above - because it's past `latest`

**Comment by isaacs** [comment]
Yes, it does not sort, sorry I didn't realize that was part of the question here.

> Q: why does the 3clear version not satisfy either range?
> A: because the code not only tests against the range but also enforces a max matching version of latest:
> https://github.com/npm/semver.npmjs.com/blob/6a29619986430438e0f629011e5d2345b47dea88/src/entry.js#L30-L38

Ok, well that's just weird imo.

> Q: why does npm cli not suggest 3clear as an upgrade option?
> A: same reason as above - because it's past latest

Probably not the right answer.  What's in your package.json?  `npm outdated` shows you what you can upgrade to, and what latest is.  If "what you can upgrade to" is higher than latest, it'll show you that.

```
$ cat package.json
{
  "name": "prerelease-semver-question",
  "version": "1.0.0",
  "dependencies": {
    "eslint-plugin-rxjs": ">=0.0.1-beta.7"
  },
  "license": "ISC"
}

$ npm ls eslint-plugin-rxjs
prerelease-semver-question@1.0.0 /Users/isaacs/dev/js/x/prerelease-semver-question
└── eslint-plugin-rxjs@0.0.1-beta.7


$ npm outdated
Package                  Current             Wanted         Latest  Location
eslint-plugin-rxjs  0.0.1-beta.7  0.0.1-beta.3clear  0.0.2-beta.11  prerelease-semver-question
```

**Comment by rarkins** [comment]
OK, thanks for that info. I think we got to the bottom of it and the authors of the package in question have kindly released a `0.0.2-*` version to ensure there's no ambiguity of ordering, which also makes it harder to test now without publishing a few dummy package versions of our own, which seems not worth it.

**Comment by rassie** [comment]
I'm afraid, this problem has gotten worse with `0.0.2-*` release:

![image](https://user-images.githubusercontent.com/23448/69855285-7c192c00-128b-11ea-9e1b-76de54afca73.png)

Any idea what's happening?

**Comment by rarkins** [comment]
Before, the 3clear release was “ahead of latest” so ignited by the > check. Now that 0.0.2-* is latest, 3clear satisfies both “is it greater than 0.0.1-beta5?” and “is it less than it equal to latest”?

**Comment by rassie** [comment]
ok, but why doesn't it see 0.0.2-beta.11 as higher version than 0.0.1-beta.5?

**Comment by rarkins** [comment]
In this case I think it's semver.npmjs.com that's being a little bit strange. The `semver` package sorts in the order you'd expect: https://runkit.com/rarkins/5de0e090a70b05001ad23f58

![image](https://user-images.githubusercontent.com/6311784/69857819-fc8e5b80-1290-11ea-9cd3-a3ae40ce6950.png)

**Comment by isaacs** [comment]
While 0.0.2-beta.11 is greater than 0.0.1-beta.5, it does _not_ satisfy the range `>0.0.1-beta.5` because of how prerelease versions are handled.

A prerelease version can never satisfy a range unless the range includes a prerelease version with the same major,minor,patch tuple.

For example, `>=0.0.2-beta.1` would be satisfied by `0.0.2-beta.11`, because there is a prerelease in the range on the tuple `0.0.2`.  However, `>=0.0.1-beta.5` would not be satisfied by `0.0.2-beta.11` because `0.0.2-beta.11` has a prerelease version outside of the `0.0.1` tuple.

This prevents `4.0.0-beta` from satisfying the range `^3.2.1`, which expands down to `>=3.2.1 <4.0.0`.  Since the `4.0.0-beta` range is "less than" 4.0.0, it would cause people to get prereleases of majors that they don't support (and, in fact, which are not yet supported or ready for release!)

Effectively, prerelease versions are "opt-in".  If you're on that version train, the range matches.  If you aren't, then it won't.

When using semver programmatically, you can treat prerelease versions like regular versions by setting the `{ includePrerelease: true }` flag in the options object passed to any method or class.

**Comment by isaacs** [comment]
From the docs: https://github.com/npm/node-semver#prerelease-tags

**Comment by Terux101** [comment]
// http://civicrm.org/licensing
(function($, _, undefined) {
  "use strict";
  var selected = 0,
    form = 'form.crm-search-form',
    active = 'a.action-item:not(.crm-enable-disable), a.crm-popup';

  function clearTaskMenu() {
    $('select#task', form).val('').select2('val', '').prop('disabled', true).select2('disable');
  }

  function enableTaskMenu() {
    if (selected || $('[name=radio_ts][value=ts_all]', form).is(':checked')) {
      $('select#task', form).prop('disabled', false).select2('enable');
    }
  }

  function displayCount() {
    $('label[for*=ts_sel] span', form).text(selected);
  }

  function countCheckboxes() {
    return $('input.select-row:checked', form).length;
  }

  function clearSelections(e) {
    /* jshint validthis: true */
    if (selected) {
      var $form = $(this).closest('form');
      $('input.select-row, input.select-rows', $form).prop('checked', false).closest('tr').removeClass('crm-row-selected');
      if (usesAjax()) {
        phoneHome(false, $(this));
      } else {
        selected = 0;
        displayCount();
      }
    }
  }

  function usesAjax() {
    return $(form).hasClass('crm-ajax-selection-form');
  }

  // Use ajax to store selection server-side
  function phoneHome(single, $el, event) {
    var url = CRM.url('civicrm/ajax/markSelection');
    var params = {qfKey: 'civicrm search ' + $('input[name=qfKey]', form).val()};
    if (!$el.is(':checked') || $el.is('input[name=radio_ts][value=ts_all]')) {
      params.action = 'unselect';
      params.state = 'unchecked';
    }
    if (single) {
      params.name = $el.attr('id');
    } else {
      params.variableType = 'multiple';
      // "Reset all" button
      if ($el.is('a')) {
        event.preventDefault();
        $("input.select-row, input.select-rows", form).prop('checked', false).closest('tr').removeClass('crm-row-selected');
      }
      // Master checkbox
      else if ($el.hasClass('select-rows')) {
        params.name = $('input.select-row').map(function() {return $(this).attr('id');}).get().join('-');
      }
    }
    $.post(url, params, function(data) {
      if (data && data.getCount !== undefined) {
        selected = data.getCount;
        displayCount();
        enableTaskMenu();
      }
    }, 'json');
  }

  /**
   * Refresh the current page
   */
  function refresh() {
    // Clear cached search results using force=1 argument
    var location = $('#crm-main-content-wrapper').crmSnippet().crmSnippet('option', 'url');
    if (!(location.match(/[?&]force=1/))) {
      location += '&force=1';
    }
    $('#crm-main-content-wrapper').crmSnippet({url: location}).crmSnippet('refresh');
  }

  /**
   * When initially loading and reloading (paging) the results
   */
  function initForm() {
    clearTaskMenu();
    if (usesAjax()) {
      selected = parseInt($('label[for*=ts_sel] span', form).text(), 10);
    } else {
      selected = countCheckboxes();
      displayCount();
    }
    enableTaskMenu();
  }

  $(function() {
    initForm();

    // Focus first search field
    $('.crm-form-text:input:visible:first', 'form.crm-search-form').focus();

    // Handle user interactions with search results
    $('#crm-container')
      // When toggling between "all records" and "selected records only"
      .on('change', '[name=radio_ts]', function() {
        clearTaskMenu();
        enableTaskMenu();
      })
      .on('click', 'input[name=radio_ts][value=ts_all]', clearSelections)
      // When making a selection
      .on('click', 'input.select-row, input.select-rows, a.crm-selection-reset', function(event) {
        var $el = $(this),
          $form = $el.closest('form'),
          single = $el.is('input.select-row');
        clearTaskMenu();
        $('input[name=radio_ts][value=ts_sel]', $form).prop('checked', true);
        if (!usesAjax()) {
          if (single) {
            selected = countCheckboxes();
          } else {
            selected = $el.is(':checked') ? $('input.select-row', $form).length : 0;
          }
          displayCount();
          enableTaskMenu();
        } else {
          phoneHome(single, $el, event);
        }
      })
      // When selecting a task
      .on('change', 'select#task', function(e) {
        var $form = $(this).closest('form'),
        $go = $('input.crm-search-go-button', $form);
        var $selectedOption = $(this).find(':selected');
        if (!$selectedOption.val()) {
          // do not blank refresh the empty option.
          return;
        }
        if ($selectedOption.data('is_confirm')) {
          var confirmed = false;
          var refresh_fields = $selectedOption.data('confirm_refresh_fields');
          var $message = '<tr>' + (($selectedOption.data('confirm_message') !== undefined) ? $selectedOption.data('confirm_message') : '') + '</tr>';
          if (refresh_fields === undefined) {
            refresh_fields = {};
          }
          $.each(refresh_fields, function (refreshIndex, refreshValue) {
            var $refresh_field = $(refreshValue.selector);
            var prependText = (refreshValue.prepend !== undefined) ? refreshValue.prepend : '';
            var existingInput = $refresh_field.find('input').val();
            $message = $message + '<tr>' + $refresh_field.html().replace(existingInput, prependText + existingInput) + '</tr>';
          });

          CRM.confirm({
            title: $selectedOption.data('confirm_title') ? $selectedOption.data('confirm_title') : ts('Confirm action'),
            message: '<table class="form-layout">' + $message + '</table>'
          })
          .on('crmConfirm:yes', function() {
            confirmed = true;
            $.each(refresh_fields, function (refreshIndex, refreshValue) {
              $('#' + refreshIndex).val($('.crm-confirm #' + refreshIndex).val());
            });
            $go.click();
          })
          .on('crmConfirm:no', function() {
            $('#task').val('').change();
            return;
          });
        }
        else if (!$(this).find(':selected').data('supports_modal')) {
          $go.click();
          $('#task').val('').select2('val', '');
        }
        // The following code can load the task in a popup, however not all tasks function correctly with this
        // So it's a per-task opt-in mechanism.
        else {
          var data = $form.serialize() + '&' + $go.attr('name') + '=' + $go.attr('value');
          var url = $form.attr('action');
          url += (url.indexOf('?') < 0 ? '?' : '&') + 'snippet=json';
          clearTaskMenu();
          $.post(url, data, function(data) {
            CRM.loadForm(data.userContext).on('crmFormSuccess', refresh);
            enableTaskMenu();
          }, 'json');
        }
      });

    // Add a specialized version of livepage functionality
    $('#crm-main-content-wrapper')
      .on('crmLoad', function(e) {
        if ($(e.target).is(this)) {
          initForm();
        }
      })
      // Open action links in a popup
      .off('.crmLivePage')
      .on('click.crmLivePage', active, CRM.popup)
      .on('crmPopupFormSuccess.crmLivePage', active, refresh);
  });

})(CRM.$, CRM._);
