### ISSUE TITLE
[FEATURE] Include changelog in release notes

### ISSUE THREAD

**Issue by JustinBeckwith** [npm/node-semver#298]
Greetings folks!  It would be rad if the changelog for a given version was included in the release notes.  Many tools that auto-submit PRs for semver major module updates will include these release notes in the PR.  For `semver`, I'm not getting anything:
https://github.com/JustinBeckwith/npmtrace/pull/8

When I went poking about, eventually I did find great release notes in the changelog:
https://github.com/npm/node-semver/blob/master/CHANGELOG.md

For tools like c8, I get the details of the change right in the release PR because they're included in the GitHub release:
https://github.com/JustinBeckwith/fileinator/pull/20

If we had the same information in the [GitHub release](https://github.com/npm/node-semver/releases/tag/v7.0.0), it would make finding the information much easier.

**Comment by isaacs** [comment]
I don't think it's reasonable to manually write up release notes for every module.  We do this for npm/cli, but that's also a major chunk of the work of cutting a release.  Is it possible to update the renovate bot to check for a CHANGELOG.md file?  Otherwise, this will probably wait for something that can automatically update github releases from the changelog entry without additional human intervention.

**Comment by JustinBeckwith** [comment]
Totally understand.  We're using automation to do exactly what you're proposing, where conventional commit messages are automatically grouped together to form the changelog, and the updating of the CHANGELOG.md and creation of the GitHub Release / tag are done at the same time.  I'm personally using [semantic release](https://github.com/semantic-release/semantic-release/) for these purposes, but it's a little loose and fast.  @bcoe wrote up [release please](https://github.com/googleapis/release-please/) which takes a more conservative approach where the release PR is automatically created, but a human has to merge the PR to cut the release with generated notes.  It may be worth exploring 🤷‍♂

**Comment by bcoe** [comment]
👋 obviously I'd be happy to help, it's my goal in 2020 to continue making some of the tools we're writing available to the community.
