### ISSUE TITLE
[FEATURE] Provide typescript typings

### ISSUE THREAD

**Issue by domoritz** [npm/node-semver#300]
The typings at @types/semver are not up to date (you cannot import `semver/functions/satisfies` for example) and it would be great to have types officially coming with the semver package.

**Comment by isaacs** [comment]
My standard reply to "add type defs":

Give me a PR with:

- a complete type definition file
- and a test that:
  - passes when the types are complete and accurate, and
  - fails when the types are incomplete or inaccurate

and I will accept it.

Adding a new devDep for the test is fine.  But without a test, I guarantee that we will break the type definitions and not notice, so it's better to just not have them than to have them be inaccurate.

**Comment by icholy** [comment]
Tell me you hate typescript without telling me you hate typescript.
