### ISSUE TITLE
[BUG] Update from 5.x to 7.x throws error when deployed

### ISSUE THREAD

**Issue by corby** [npm/node-semver#305]
# What / Why
I just upgraded from semver@5.x to semver@latest and now my react app crashes
Seems to be related to the lazyRequire function.
Looks like webpack is optimizing out the functions.

## When
import semver from "semver";
....
this.isAppValid = ver => {
  return semver.valid(ver) !== null;
}

## Where
semver_sync:2 Uncaught Error: Cannot find module './functions/valid'
    at webpackEmptyContext (semver_sync:2)
    at lazyRequire (index.js:3)
    at Object.get [as valid] (index.js:10)
    at StrapTable.eval [as isAppVerValid] (userOverview.jsx:409)

### Current Behavior
crash

### Steps to Reproduce
This only happens when I run webpack to build a deployment package (mode doesn't matter, happens in both production and development modes)

### Expected Behavior
work like 5.x

**Comment by isaacs** [comment]
Use this:

```js
import semver from "semver/preload.js";
```

**Comment by corby** [comment]
That hack worked. thanks.
But it's still a hack.
is there a way to handle this so I don't have to use undocumented code to use the library with webpack?

**Comment by tomquas** [comment]
fwiw, i upgraded from 6.3.0 and had the same issue. i'd also prefer to not apply 'special knowledge' via importing semver/preload... thx

**Comment by isaacs** [comment]
It was in the changelog, but I updated the readme as well on 70d9fb3f1c128227a3cd911867edb07a54260cad.

**Comment by isaacs** [comment]
> But it's still a hack.

It's... not a hack tho?  It's very much intended for this exact purpose, that's why it's there.
