### ISSUE TITLE
[BUG] Upgrading to version 7 causes webpack error

### ISSUE THREAD

**Issue by kaiyoma** [npm/node-semver#306]
We're currently using semver 6.3.0, but if we upgrade to the latest version (7.1.1), we start getting webpack errors:

```
WARNING in ./node_modules/semver/index.js 3:51-64
Critical dependency: the request of a dependency is an expression
```

Based on the usage notes in the README, it would seem that we now need to use `require` with `semver/preload`? Why?

This is how we've been importing from semver for a while now, but this doesn't work anymore:

```
import { coerce, gte } from 'semver';
```

If I try to import from `semver/preload`, then I start getting TypeScript errors because that string doesn't match a known module name. What's the correct `import` API syntax here?

**Comment by isaacs** [comment]
How does typescript know about module names?  The file is there, `require` works just fine.  I'd be happy to accept a PR to make it play nice with typescript, but as it is working fine when used as intended, that is an enhancement rather than a bug that needs to be fixed.

**Comment by kaiyoma** [comment]
TypeScript and the `import` syntax are both quite popular, so it doesn't seem like an "enhancement" to me, especially since this new behavior is a regression from version 6.x of this package.

I was able to get the semver package working again by doing this:

```
import { coerce, gte } from 'semver/preload';
```

However, as mentioned before, the TypeScript checker is unhappy now:

```
Could not find a declaration file for module 'semver/preload'.
```

This is the types package we're using: https://www.npmjs.com/package/@types/semver

The last version is 6.2.0, so I'm guessing you need to release a new version that has the types for version 7 of the package?

**Comment by isaacs** [comment]
> The last version is 6.2.0, so I'm guessing you need to release a new version that has the types for version 7 of the package?

I'm not the one who wrote or maintains that package.  According to the readme:

> These definitions were written by Bart van der Schoor https://github.com/Bartvds, BendingBender https://github.com/BendingBender, Lucian Buzzo https://github.com/LucianBuzzo, Klaus Meinhardt https://github.com/ajafff, and ExE Boss https://github.com/ExE-Boss.

So it looks like @Bartvds, @BendingBender, @LucianBuzzo, @ajafff, or @ExE-Boss are the ones to ask about an update, maybe?

**Comment by isaacs** [comment]
> TypeScript and the import syntax are both quite popular, so it doesn't seem like an "enhancement" to me, especially since this new behavior is a regression from version 6.x of this package.

It was never a design requirement for this module to work with TypeScript.  The fact that it did is because some folks saw fit to write a type definition for in the DefinitelyTyped repo.

So, yes, adding that new requirement absolutely is an enhancement, because you're asking for a change to the intended design of the module.  It's not a regression in semver, because it's not something that was ever supported to begin with.  It is a breaking change, of course, but you can expect to have to update your code when moving from version 6 to version 7.  I think everyone using this module in particular should be able to appreciate that :)  To the extent that it is a bug or regression, it's in the type defs, not here.

**Comment by kaiyoma** [comment]
Ah okay, I didn't realize that the TypeScript definitions were handled by different authors here. Sounds like we need an issue in that project as well. I'll open one and cross-link the two.

**Comment by kaiyoma** [comment]
DefinitelyTyped issue: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/41326

**Comment by KagamiChan** [comment]
I'll switch to [compare-versions](https://www.npmjs.com/package/compare-versions) because it seems more browser env friendly

**Comment by haltman-at** [comment]
Just popping into say this has been an [issue](https://github.com/trufflesuite/truffle/issues/2732) for us as well, also had to downgrade to v6 to fix it.

**Comment by isaacs** [comment]
Anyone wanna check and see if this fixes the issues you're having?

```
npm in npm/node-semver#isaacs/remove-lazy-require
```

If so, pop over to #311 and let me know.
