### ISSUE TITLE
[QUESTION] semver >= 7.1.0 forces node >= 10

### ISSUE THREAD

**Issue by mobilutz** [npm/node-semver#312]
# What / Why
* semver >= 7.1.0 is forcing node >= 10

Although I really aggree that node should be updated asap, the change in semver 7.1.0 broke our apps development npm install.
Our CI didn't fail, because we don't install development dependencies on it.

I question, if the hard enforcing on node version in a package that is mostly used in devDepenencies is really the best approach.

## Where
* when a npm update is happening which leads to semver being updated

## Who
* n/a

## References
* n/a

**Comment by erdahuja** [comment]
Same, if i upgrade to node 10, my other packages are not compliant to that. @mobilutz

**Comment by Apollon77** [comment]
Forcing a new nodejs version should be considered as breaking change and reflected by a major version increase. Far from ideal. Any chance to get that fixed?

**Comment by mobilutz** [comment]
We worked with this situation, and upgrade our node to >=10, so this issue is not really open for me anymore.

And isaacs did add some more very useful insights here:
https://github.com/npm/node-semver/commit/d61f828e64260a0a097f26210f5500e91a621828#r37027980

As I really don't need this anymore, I will close this issue.
