### ISSUE TITLE
[QUESTION] Pre-release handling border cases

### ISSUE THREAD

**Issue by raphaelzulliger** [npm/node-semver#317]
# Feature or bug?
I was wondering how node-semver handles some of the border cases related to versions with 'pre-releases'. Thereby, I encountered some behavior for which I'm not sure whether they are bugs or whether I don't yet fully understand semver.org

## Where
I've added [some tests](/raphaelzulliger/node-semver/commit/0c747f5cfdda27cd580a79dc0384cffe48715161), which all succeed (unless they're commented out).

I'd be interested in your opinion.

**Comment by isaacs** [comment]
Yes, this is working as intended.  See: https://github.com/npm/node-semver#prerelease-tags
