### ISSUE TITLE
semver regular expression does not follow Semantic Versioning standard format

### ISSUE THREAD

**Issue by petermichaux** [npm/node-semver#32]
```
var semver = "\\s*[v=]*\\s*([0-9]+)"        // major
           + "\\.([0-9]+)"                  // minor
           + "\\.([0-9]+)"                  // patch
           + "(-[0-9]+-?)?"                 // build
           + "([a-zA-Z-+][a-zA-Z0-9-\.:]*)?" // tag
```

The above is the foundation of parsing in this module but it does not follow the format from the Semantic Version standard http://semver.org/ 

```
/^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
```

The first capturing group is "major".

The second capturing group is "minor".

The third capturing group is "patch".

The forth capturing group is "prerelease" (not including the preceding dash delimiter between patch and prerelease).

The "build" is non-capturing because it is not to be used in any comparisons.

**Comment by bfloydgsn** [comment]
Slightly better regex for 2.0.0-rc.2
([0-9]+)\.([0-9]+)\.([0-9]+)(?:(\-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-\-\.]+)?

**Comment by isaacs** [comment]
@bfloydgsn You're commenting on a 3-year-old issue.  This is historical, and not a good place to put new things.

If you'd like to make an improvement or have found a bug, please open a new PR or issue.  Thanks.
