### ISSUE TITLE
[BUG] semver.validRange(`1.x.x`) includes `-0` prerelease suffix since v7.3.1 & v7.3.2

### ISSUE THREAD

**Issue by gr2m** [npm/node-semver#322]
# What / Why

```js
semver.validRange('1.x.x')
// returns ">=1.0.0 <2.0.0" in 7.3.0
// returns ">=1.0.0 <2.0.0-0" in 7.3.1, 7.3.2
```

## When

* n/a

## Where

* n/a

### Current Behavior

* n/a

### Steps to Reproduce

* Test case at https://runkit.com/gr2m/npm-node-semver-v7-3-1-bug

### Expected Behavior

* n/a

## Who

* n/a

## References

* https://github.com/semantic-release/semantic-release/issues/1524

**Comment by eemeli** [comment]
This was introduced in #320, because the previously calculated `validRange` for e.g. `1.x.x` would include `2.0.0-0` and other prerelease versions of the maximal endpoint.

**Comment by gr2m** [comment]
@eemeli just to be sure: was this an intentional change? Because if so, I'd expect it to be released as v8.0.0 due to change of the API?

**Comment by eemeli** [comment]
Yes, this was an intentional change. I asked @isaacs elsewhere about the API change and got this answer:

>it might be a breaking change from 6, not sure.
>but it's not from 7
>I think the expectation is that `1.x` should not intersect `2.0.0-0`, regardless of whether `includePrerelease` is set or not.
>I haven't typically treated the specific set of comparators in range parsing as a part of the API per se.

**Comment by gr2m** [comment]
okay, cheers 👍
