### ISSUE TITLE
[BUG] Possible 'gtr' / 'ltr' inconsistency with spec

### ISSUE THREAD

**Issue by McSherry** [npm/node-semver#328]
# What / Why
I'll preface this by saying I don't use `node-semver`, but I do maintain a tool that aims to be compatible with its version ranges. This issue is based off reading documentation and test cases.

The `gtr` and `ltr` functions are documented as "return[ing] `true` if the version is greater/less than all the versions possible in the range." The following two test cases, to me, look inconsistent with that:

- `0.7.2-beta > 0.7.x` ([link][1.1])

- `1.3.0-alpha < >1.2.3` ([link][1.2])

I don't know whether this is exhaustive, these are just two cases that stood out to me.

[1.1]: https://github.com/npm/node-semver/blob/v7.3.2/test/fixtures/version-gt-range.js#L64
[1.2]: https://github.com/npm/node-semver/blob/v7.3.2/test/fixtures/version-lt-range.js#L68

### Current Behavior

Tests for `node-semver` indicate that:

- The version `0.7.2-beta` is greater (`gtr`) than the range `0.7.x`

- The version `1.3.0-alpha` is less (`ltr`) than the range `>1.2.3`

### Expected Behavior

For the first case, `0.7.x` decomposes into `>=0.7.0 <0.8.0`. This matches `0.7.3`, which has higher precedence than `0.7.2-beta` and so `0.7.2-beta` cannot be "greater than all versions possible" and the `gtr` function should return false here.

In the second case, `>1.2.3` does not decompose but does match `1.2.4`. This has lower precedence than `1.3.0-alpha`, and so `1.3.0-alpha` cannot be "less than all versions possible" and the `ltr` function should return false here.

I initially thought for the second case that pre-release versions being excluded from range comparison by default could be the reason, but if that were true then the first case would be inconsistent with this.

## Who
@isaacs

**Comment by Thefolle** [comment]
Hello, I am new to the tool but I would like to contribute.

I've skimmed the code this morning and my conclusion, as of now, is that the module does not probe prelease tags by itself. Both for internal functions (e.g. gtr, outside) and for the CLI you should tell semver that the version string includes a prerelease tag.

For internal functions, pass the `{ includePrerelease: true }` object as the `options` parameter; at CLI level, pass `--include-prerelease` instead.

In `version-gt-range.js` file add the option to the last tuple:
```js
  ['0.7.x', '0.7.2-beta', { includePrerelease: true } ],
 ```
 The test now fails meaning that the version is not greater than the range, which is correct.
 
 For any doubt on my view, give me a reply ;)

**Comment by wraithgar** [comment]
The prerelease tags are the reason for the apparent inconsitency, @Thefolle is correct.
