### ISSUE TITLE
[QUESTION] Should '*' include prereleases

### ISSUE THREAD

**Issue by wheresrhys** [npm/node-semver#329]
# What / Why
In my package [fetch-mock](https://www.npmjs.com/package/fetch-mock) I declare a peerDependency of `node-fetch: '*'`

According to the [documentation](https://docs.npmjs.com/misc/semver#x-ranges-12x-1x-12-) this should allow any version:

> * := >=0.0.0 (Any version satisfies)

The behaviour I'm seeing is that it will only ever install non-prereleases of node-fetch ( node@12.6.1 and presumably the npm version it bundles by default - I'm seeing the behaviour in https://repl.it/repls/HastyGregariousServerapplication)

I have 3 questions

1. Is this behaviour correct - should '*' really exclude prereleases? In other words, is this a bug in npm's treatment of peerDependencies
2. Assuming the behaviour is correct, I guess the docs above mean `*` is an alias for `>=0.0.0`, and it's misleading to describe this as 'Any version satisfies' - it would be more correct to change the documentation to read 'Any non-prerelease version satisfies'
3. Also assuming the behaviour is correct, is there any way I can genuinely express a dependency on a package that will allow any version, including prereleases?

**Comment by wheresrhys** [comment]
Update - I can't recreate locally. I would guess that repl.it is doing something in addition to `npm install` to force peerDependencies. But my questions about the expected behaviour still stand. Thanks

**Comment by matheo** [comment]
THIS!
I'm having a problem in my `lerna` repo because while I'm publishing canary releases of my packages, this check made by lerna:
```
semver.satisfies('16.0.0-beta-0`, '*')
```
is returning `false` and then my whole dependency tree gets screwed because from there, lerna's PackageGraph is not built correctly!

This was quite a surprise because a `16.0.0-beta.0` seems far beyond `>1.0.0` according to the definition :(

**Comment by wheresrhys** [comment]
@lukekarrys I'm a bit confused why you'd acknowledge the point about the docs needing improvement but close this without (as far as I can see) addressing that point.

**Comment by lukekarrys** [comment]
You're right, I'm not sure why I did that. Leaving this open with the action to improve the docs around prerelease versions, specifically the phrasing `Any version satisfies`.

**Comment by wheresrhys** [comment]
Thank you 😄
