### ISSUE TITLE
[QUESTION] How do I check if a version matches a certain pre-release?

### ISSUE THREAD

**Issue by felipecrs** [npm/node-semver#347]
I have the version `1.0.0-beta.4`. I want to check if this version matches the `1.0.0-beta` prerelease version, in other words, I want to know if the version belongs to the `beta` of `1.0.0`.

Currently, this is what I can do to achieve the same:

```sh-session
$ version=1.0.0-beta.2
$ range=1.0.0-beta
$ semver -p -r ">=$range <$(semver -i patch $range)" $version
1.0.0-beta.2
```

The problem is that I have to calculate the next patch version manually. Isn't there a more straightforward alternative?

**Comment by lukekarrys** [comment]
You can use `semver.satisfies` for this:

```
> semver.satisfies("1.0.0-beta.5", "^1.0.0-beta")
true
```

**Comment by felipecrs** [comment]
Makes sense. Although this does not seem available from the command line.

Anyway, thank you!
