### ISSUE TITLE
Why is prerelease('1.2.3-alpha.1') correct and rerelease('^1.2.3-alpha.1') not

### ISSUE THREAD

**Issue by wukaikailive** [npm/node-semver#348]
```
semver.prerelease('1.2.3-alpha.1') // => ['alpha',1]

semver.rerelease('^1.2.3-alpha.1') // => null
```
Why is there such a difference? I just want to get an exact version number from `'^1.2.3-alpha.1'`,just like `1.2.3-alpha.1`, or what should I do?

sermer version: ^7.3.2

node version: v12.13.0

**Comment by MatthiasEngh** [comment]
`^1.2.3-alpha.1` is a range, not a version like `1.2.3-alpha.1`

**Comment by lukekarrys** [comment]
If you check the lowest returned comparator after parsing a range, you should get a semver instance of that version:

```
> new s.Range('^1.2.3-alpha.1').set[0][0].semver.prerelease
[ 'alpha', 1 ]
```
