### ISSUE TITLE
[QUESTION] Is there a way to get the increment level between two versions? 

### ISSUE THREAD

**Issue by markcellus** [npm/node-semver#355]
# What / Why
I have a use-case where I'd like to get the increment level (e.g. `patch`, `minor`, `major`) between two versions. For example, a function that will return `major` if passed `4.6.0` and `5.0.0`.  Is there already a way to do this? If not, what's the best workaround to achieve this behavior?

## Where

* n/a

## Who

* n/a

## References

* n/a

**Comment by lukekarrys** [comment]
I think `diff` is what you are looking for.

> diff(v1, v2): Returns difference between two versions by the release type (major, premajor, minor, preminor, patch, prepatch, or prerelease), or null if the versions are the same.
