### ISSUE TITLE
[BUG] 16.0.0-head fails satisfies test for "^8.13.0 || >=10.10.0"

### ISSUE THREAD

**Issue by nc** [npm/node-semver#356]
# What / Why
> namitchadha@Namits-MacBook-Air functions % node --version
> v16.0.0-head

> semver.satisfies('16.0.0-head', "^8.13.0 || >=10.10.0");
> false

# Expected behaviour

It passes

**Comment by lukekarrys** [comment]
You can use the `includePrerelease: true` option.

```
> s.satisfies('16.0.0-head', "^8.13.0 || >=10.10.0", { includePrerelease: true });
true
```
