### ISSUE TITLE
diverse result for satisfies range

### ISSUE THREAD

**Issue by artola** [npm/node-semver#361]
Unexpected difference for the comparison using:

`satisfies('1.0.0', '<=1.*')` returns `true` OK
`satisfies('1.0.0', '<1.*')` returns `false` FAILS

## When
* n/a

## Where
  * npm/node-semver  ("semver": "^7.3.0")

### Current Behavior

* n/a

### Steps to Reproduce
```js
const semver = require('semver');

console.log('==>', semver.satisfies('1.1.0', '<=1.*') === semver.satisfies('1.1.0', '<1.*'));
```

### Expected Behavior
I would expect that `<1.*` and `<=1.*` behave in the same way, something like `<= 1.99999999999999` (max value possible)
in similar way for the opposite case  that `>1.*` and `>=1.*` behave in the same way, something like `>= 1.0` (min value possible)

## Who

* n/a

## References
OK: https://jubianchi.github.io/semver-check/#/%3C%3D1.*/1.1
FAILS: https://jubianchi.github.io/semver-check/#/%3C1.*/1.1

**Comment by lukekarrys** [comment]
I agree that this looks strange at first glance, but I don't think this is a bug.

If you look at the ranges generated you can see that `<=` means less than the upper bound and `<` means less than the lower bound:

```js
semver.validRange('1.*')   // >=1.0.0 <2.0.0-0
semver.validRange('<=1.*') // <2.0.0-0
semver.validRange('<1.*')  // <1.0.0-0
```

So it makes sense that `1.1.0` satisfies `<=1.*` but not `<1.*`.
