### ISSUE TITLE
[BUG] unexpected semver.maxSatisfying(versions, semver.validRange(version)) behaviour

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [npm/node-semver#382]
# What / Why

* `semver.validRange('24')` returns `'>=24.0.0 <25.0.0-0'`, which is seemingly Okay (`24` is user input),
* `semver.maxSatisfying(['24.0'], '>=24.0.0 <25.0.0-0')` returns `null`, which seems to indicate the lib. is contradicting itself (`24.0` is from a list of available versions).

## Where

* v7.3.5

### Current Behavior

* check "What / Why?"

### Expected Behavior

* `semver.maxSatisfying(['24.0'], '>=24.0.0 <25.0.0-0')` should return `24.0`.

## References

* https://github.com/erlef/setup-beam/pull/34
* https://jubianchi.github.io/semver-check/#/24/24.0 (maybe this is not a valid reference, but it illustrates my point)

**Comment by lukekarrys** [comment]
The first parameter of `maxSatisfying` is an array of versions, but `24.0` is a range not a version.

```
> semver.maxSatisfying(['24.0'], '>=24.0.0 <25.0.0-0')
null
> semver.maxSatisfying(['24.0.0'], '>=24.0.0 <25.0.0-0')
'24.0.0'
```

I would recommend calling `semver.coerce` on the input first to convert it from a range-link into a version:

```
> semver.maxSatisfying([semver.coerce('24.0').version], '>=24.0.0 <25.0.0-0')
'24.0.0'
```

**Comment by paulo-ferraz-oliveira** [comment]
Yeah, this is what we ended up doing, a few months back. Thanks.
