### ISSUE TITLE
[QUESTION] Which is bigger 2.0.0-0" or "1.2.4-beta.2

### ISSUE THREAD

**Issue by jaceyi** [npm/node-semver#391]
> `^1.2.3-beta.2 := >=1.2.3-beta.2 <2.0.0-0` Note that prereleases in the `1.2.3` version will be allowed, if they are greater than or equal to `beta.2.` So, `1.2.3-beta.4` would be allowed, but `1.2.4-beta.2` would not, because it is a prerelease of a different `[major, minor, patch]` tuple.

# What / Why
`^1.2.3-beta.2 := >=1.2.3-beta.2 <2.0.0-0` but `1.2.4-beta.2` would not, Which is bigger `2.0.0-0` or `1.2.4-beta.2`.

**Comment by ljharb** [comment]
I'm not sure how any definition of "bigger" could think that a v1 is bigger than a v2.

**Comment by lukekarrys** [comment]
I think this question has been answered. Please reopen if that's not the case, or open a new issue.
