### ISSUE TITLE
[BUG] Something wrong with the method semver.satisfies if the version were appended a hyphen

### ISSUE THREAD

**Issue by YijunShen** [npm/node-semver#397]
# What / Why

> Something wrong with the method semver.satisfies when appending a hyphen
(node-semver version: 0.8.0)

### Current Behavior

* `semver.satisfies('0.9.4-4', '< 0.9.6-12')`
 return the wrong value 'False'
------------------------
* BTW, but when I checked: 
* `semver.satisfies('0.9.4', '< 0.9.6-12')`, AND 
 `semver.satisfies('0.9.6-4', '< 0.9.6-12')`
 It both return the right value 'True'

### Expected Behavior

* return a 'True' value

**Comment by ljharb** [comment]
That’s because they’re prereleases. Try passing `{ includePrereleases: true }`

**Comment by YijunShen** [comment]
You are so kind~
 It works, thank you~
