### ISSUE TITLE
[QUESTION] `semver.valid` behavior with the input such as `17`

### ISSUE THREAD

**Issue by Shinyaigeek** [npm/node-semver#414]
# What / Why

Hi team !

Thank you for developing this nice library!

While I use `semver`, I have one question, which is about the behavior of `semver.valid`.

As far as I read [npm Docs dependencies section](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#dependencies) and play [npm semver calculator](https://semver.npmjs.com/), I feel semantic version `17` is valid and has the same meaning as `17.x`. Actually, `semver.validRange` returns assumed value with the input such as `17`. However, `semver.valid` returns null with the input such as `17`. I feel strange about this behavior, so I would appreciate it if you could tell me why `semver.valid`’s output is like this.

I searched for other issues, but I'm sorry if it's a duplicate of an existing issue.

**Comment by ljharb** [comment]
Because 17 is a range, and not a version, it’s a valid range but an invalid version.

**Comment by Shinyaigeek** [comment]
I see, Thank you for reply!👍
