### ISSUE TITLE
[BUG] Java version 1.8.0_312 does not satisfy

### ISSUE THREAD

**Issue by adminy** [npm/node-semver#428]
# What / Why

> 1.8.0_312      <--- should work when calling `satisfies`

## When

* satisfies('1.8.0_312', '*')

## Where

* npm public registry

### Current Behavior

* filters it out

### Steps to Reproduce

* run `satisfies('1.8.0_312', '*')`

### Expected Behavior

* should not filter it out

## Who

* n/a

## References

* n/a

**Comment by ljharb** [comment]
Why should it work? `0_312` isn't a valid semver version.
