### ISSUE TITLE
Why new minor version 7.3.6 is incompitable with node 13.14.0

### ISSUE THREAD

**Issue by EliseevNP** [npm/node-semver#447]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

error semver@7.3.6: The engine "node" is incompatible with this module. Expected version "^10.0.0 || ^12.0.0 || ^14.0.0 || >=16.0.0". Got "13.14.0"

### Expected Behavior

It's should be compitable or new version should be 8.0.0

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- yarn: v1.22.4
- npm:
- Node: 13.14.0
- OS:
- platform:

**Comment by kburton** [comment]
Additionally, `lru-cache ^7.4.0` is not compatible with node 10.

**Comment by ljharb** [comment]
Indeed; v7.0.0 had no engines declaration at all, v7.1.0 set it to `>= 10`, and v7.3.6 was a breaking change both for changing `engines.node` and for upgrading `lru-cache` to v7.

**Comment by ireinhart** [comment]
Same here... is https://github.com/npm/node-semver/pull/434 the issue?

**Comment by ljharb** [comment]
@ireinhart i don't think so; #442 and #433 certainly are though.

**Comment by pjohnmeyer** [comment]
@archm49 I'm not sure why I was @-ed into this so I'm unsubscribing; you'll need to @-me again w/ some context if I'm expected to participate

**Comment by manjeetbrar91** [comment]
facing same issue. or production deployment stuck due this issue. please provide solution.

**Comment by pbadenski** [comment]
Sure this shouldn’t be a patch version change, but if you’re still on a non-maintained odd-numbered version 1.5 years after EOL you should really revisit your security processes...
