### ISSUE TITLE
[BUG] No matching version found for semver@7.3.6

### ISSUE THREAD

**Issue by jbexx** [npm/node-semver#452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When installing semver I'm met with an error that there is no matching version for semver@7.3.6.

When install @latest, it installs 7.3.5

### Expected Behavior

I expect the latest published version of 7.3.6 to be available for install

### Steps To Reproduce

Open terminal
run `npm i -g semver@7.3.6`
see Error
`npm ERR! code ETARGET`
`npm ERR! notarget No matching version found for semver@7.3.6.`
`npm ERR! notarget In most cases you or one of your dependencies are requesting`
`npm ERR! notarget a package version that doesn't exist.`

### Environment

- npm: 8.1.0
- Node: 16.13.0
- OS: MacOS 12.0.1
- platform: Macbook Pro

**Comment by ljharb** [comment]
Have you tried npm v8.6? What does `npm config --get registry` print out?

**Comment by jbexx** [comment]
ah!  Good call on the registry.  I have a private registry cache that is checked before going to npm and for some reason it was getting stuck and not going out to npm's registry to get semver.  
Im sorry for the trouble @ljharb, will close the issue
