### ISSUE TITLE
[QUESTION] includePrerelease usage

### ISSUE THREAD

**Issue by bz888** [npm/node-semver#464]
Hey, just wondering how do you use the prerelease tag in `validRange`
e.g. 
` const validated = valid('1.2.0-19', { includePrerelease: true})`

With my understanding of `includePrerelease` this would result to `null`.
However, currently it returns `1.2.0-19`
Is there perhaps another more suited method I should be looking at? 

Thank you in advance~

**Comment by ljharb** [comment]
Why would that be invalid? It's a range of one.

**Comment by bz888** [comment]
Is there a build-in method that checks for the `-19`  part ? 
If there is a `-19` returns invalid

**Comment by bz888** [comment]
Sorry, I mistyped. I was meant to say `includePrerelease: false`

**Comment by ljharb** [comment]
A range won’t implicitly include prereleases when that option is set to false, but that is an exact version. This behavior seems correct to me.

**Comment by bz888** [comment]
Is there perhaps another way to identify an prerelease using semver ?

**Comment by ljharb** [comment]
Are you looking for the [prerelease](https://github.com/npm/node-semver/blob/main/functions/prerelease.js) function?

**Comment by bz888** [comment]
Something similar I guess.
But mainly looking for if i can accomplish these conditions with one function: 
`1.2.0-20` or `^1.2.0-20` fail (any version that supports pre release would fail)
`>=1.2.20` pass
`*` pass
`1.2.0` pass

or would I have to layer a bunch of semver functions together to accomplish this ?

**Comment by ljharb** [comment]
`prerelease(version) === null` tells you exactly that.

**Comment by bz888** [comment]
Oh ! thank you so much!

**Comment by lukekarrys** [comment]
I think this question has been answered. If not, please reopen or open a new issue.
