### ISSUE TITLE
[BUG] satisfies is returning wrong result when used with tilde(~) range

### ISSUE THREAD

**Issue by iKrishnaSahu** [npm/node-semver#466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`semver.satisfies('5.6.2', '~5.6.3')` is returning false

### Expected Behavior

`semver.satisfies('5.6.2', '~5.6.3')` should return true

### Environment

- npm: 8.15.1 
- Node: 16.15.1
- OS: Windows
- platform: Dell

**Comment by ljharb** [comment]
5.6.2 is less than 5.6.3, so it should return false. ~5.6.3 is not 5.6.x, it’s 5.6.3 or greater, but less than 6.0.0

**Comment by iKrishnaSahu** [comment]
Yes. I just figured it out. 
Thanks @ljharb
