### ISSUE TITLE
[FEATURE?] -  Test if exact release (no wildcards)

### ISSUE THREAD

**Issue by dpgeekzero** [npm/node-semver#469]
When processing version requests I have a case where we're manually checking to see if the version string includes a wildcard character and branching to a different flow.

Would it be reasonable to have a function like isStatic to do that test internally with all supported wildcards? 
It seems like something I would expect to exist, but I haven't seen it.

**Comment by lukekarrys** [comment]
Can you give an example of the types of inputs you're testing on? Also what do you consider a wildcard character for your use case? Would it be anything that constitutes a range (ie `^`, `~`, `*`, etc)?

I might be missing something, but it seems like anything that passes `semver.valid()` is an exact version?

```
> semver.valid('1.0.0')
'1.0.0'
> semver.valid('1.0.*')
null
> semver.valid('^1.0.0')
null
> semver.valid('>1.0.0')
null
> semver.valid('~1.0.0')
null
> semver.valid('1.0.0-pre.4-BUILD')
'1.0.0-pre.4-BUILD'
>
```
