### ISSUE TITLE
[ENHANCEMENT]: support prereleases in coerce

### ISSUE THREAD

**Issue by Nokel81** [npm/node-semver#473]
Currently the exported `coerce` function does not support having the pre release information as part of the returned data.

For example:

```js
const { coerce } = require("semver")

// Current behaviour
coerce("1.9") // 1.9.0
coerce("1.9-dev") // throw

// Future behaviour
coerce("1.9-dev", { coercePrerelease: true }) // 1.9.0-dev
```

**Comment by Shakeskeyboarde** [comment]
Even better, the documentation actually says the `includePrerelease` option is supposed to work now.

**Comment by wraithgar** [comment]
Fixed by https://github.com/npm/node-semver/pull/671
