### ISSUE TITLE
[FEATURE] - A function return versions in the list satisfies the range

### ISSUE THREAD

**Issue by lvqq** [npm/node-semver#503]
A function returns versions in the list satisfies the range, similar to the function `maxSatisfying(versions, range)`, but returns the matched version list

### Usage
```
satisfyRange(versions, range)
```

### Example
```
satisfyRange(['v1.0.0', 'v2.0.0', 'v2.0.1'], '2')

// ['v2.0.0', 'v2.0.1']
```

**Comment by ljharb** [comment]
Is this different than `['v1.0.0', 'v2.0.0', 'v2.0.1'].filter(v => satisfies(v, '2'))`?

**Comment by lvqq** [comment]
Maybe sort from lowest to highest by default?
