### ISSUE TITLE
[BUG] semver.satisfies return wrong value 

### ISSUE THREAD

**Issue by VMT01** [npm/node-semver#505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using `semver.satisfies` returns the incorrect value when comparing two greater or equal version

By comparision you can get:
```js
semver.satisfies("0.4.24", "^0.4.24 && 0.4.24")
false
```

### Expected Behavior

`semver.satisfies("0.4.24", "^0.4.24 && 0.4.24")` should return true

### Steps To Reproduce

1. In node shell
2. With the current latest version of semver installed
3. Run `semver.satisfies("0.4.24", "^0.4.24 && 0.4.24")`
4. False is return

### Environment

- npm: 6.14.17
- Node: 14.20.0
- OS: Ubuntu 22.04
- platform: Lenovo Thinkpad E14

**Comment by ljharb** [comment]
Since `^0.4.24` alone satisfies it (the `&& 0.4.24` is redundant) I'd definitely expect `true` here.

**Comment by VMT01** [comment]
Yes if only the range is `^0.4.24` the correct answer of course is `true`, but I don't know why when I add `&& 0.4.24` into the range then semver returns the answer `false` as you can see in picture below
![image](https://user-images.githubusercontent.com/30618460/203923181-dd7d2912-f37f-4c07-97de-cdefb0fd5ffe.png)

**Comment by ljharb** [comment]
oh wait. does semver even _have_ `&&`? i think the valid range is `^0.4.24 0.4.24`.

What does `semver/ranges/valid` report for the one with `&&`?

**Comment by VMT01** [comment]
oh I see, now it returns true. I though semver has `&&` because there is one example with `||` and it works normally.
The problem now solved, let me close this comment
