### ISSUE TITLE
[FEATURE] Check if a definition is a simple range

### ISSUE THREAD

**Issue by rentalhost** [npm/node-semver#508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Suggestion

Currently there is no way to validate that the _semver_ is a simple/unique range. For example, `^8.0` is a simple range, while `^8.0 || ^9.0` or `>=8.0 <9.0` are composite ranges.

I'm working on an extension for vscode that should only work on simple versions, as dealing with more complex versions is much more difficult.

**Comment by ljharb** [comment]
I’m not familiar with those differentiations - a range is a range. However, i would expect that you could use the Range constructor and look at the parts in the resulting instance?

**Comment by lukekarrys** [comment]
Internally semver parses `^8` to `>=8.0.0 <9.0.0-0`, so there's not really a way to do what you want outside of manually checking that the raw semver string matches the formats you want to support.

`semver` does include the regular expressions used internally to get some of this information, but it's up to you which ones you want to check for.

For example, to see if a string is a `^` semver range (in loose mode):

```
> semver.re[semver.tokens.CARETLOOSE].test('^8')
true
> semver.re[semver.tokens.CARETLOOSE].test('>=8')
false
> semver.re[semver.tokens.CARETLOOSE].test('>=8 <9.0')
false
```
