### ISSUE TITLE
[BUG] satifies >= does not work with alphanumeric version

### ISSUE THREAD

**Issue by witoldwegner** [npm/node-semver#520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
semver.satisfies('9.0.0-rc', '>=6.0.0')
--> false

```
```
semver.satisfies('20.0.0-nightly20230223', '>= 6.0.0')
--> false
```

### Expected Behavior

apparently 9.0.0-rc and 20.0.0-nightly20230223 are >=6.0.0 and therefore semver should return true

### Environment

- npm: 6.14.16
- Node: v18.11.0
- OS: Mac Os Ventura 13.1
- platform: node
- semver: 7.3.8

**Comment by ljharb** [comment]
Pass in the `includePrereleases: true` option. Prereleases are explicitly not included in non-prerelease semver ranges by default.

**Comment by witoldwegner** [comment]
Thanks, I wasn't aware of this
