### ISSUE TITLE
[BUG] `intersects(r1, r2, options)` function returns `true` if the not intersected range `< 0.0.0` and `0.x` are supplied

### ISSUE THREAD

**Issue by sounisi5011** [npm/node-semver#521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Range `< 0.0.0` (or range `< 0.0.0-0` if the `includePrerelease` option is `true`) should not intersect with all ranges. However, the `intersects(r1, r2, options)` function returns `true` when comparing ranges `< 0.0.0` (`< 0.0.0-0`) and X-Range.

### Expected Behavior

- Returns `false` if compared to range `< 0.0.0` if the `includePrerelease` option is `false`
- Returns `false` if compared to range `< 0.0.0-0` if the `includePrerelease` option is `true`

### Steps To Reproduce

```js
const semver = require('semver'); // Import semver@7.3.8

// This returns `false`, which is as expected since the two ranges do not intersect
semver.intersects('< 1.0.0', '1.0.0', { includePrerelease: false }) === false

// These also return `false`
semver.intersects('< 1.0.0', '1.x', { includePrerelease: false }) === false
semver.intersects('< 0.0.0', '1.x', { includePrerelease: false }) === false
semver.intersects('< 0.0.0', '0.1.x', { includePrerelease: false }) === false
semver.intersects('< 0.0.0', '0.0.0', { includePrerelease: false }) === false

// These return `true` because they intersect if a pre-release is included
semver.intersects('< 1.0.0', '1.x', { includePrerelease: true }) === true
semver.intersects('< 0.0.0', '0.x', { includePrerelease: true }) === true

// However, when compared to the X-Range, this returns `true` instead of `false`
semver.intersects('< 0.0.0', '0.0.x', { includePrerelease: false }) !== false
semver.intersects('< 0.0.0', '0.x', { includePrerelease: false }) !== false
semver.intersects('< 0.0.0', '0', { includePrerelease: false }) !== false
semver.intersects('< 0.0.0-0', '0.0.x', { includePrerelease: true }) !== false
semver.intersects('< 0.0.0-0', '0.x', { includePrerelease: true }) !== false
semver.intersects('< 0.0.0-0', '0', { includePrerelease: true }) !== false

// Whether the range `< 0.0.0` is an X-range or not does not affect the result
semver.intersects('< 0', '0.0.0', { includePrerelease: false }) === false
semver.intersects('< 0.x', '0.0.0', { includePrerelease: false }) === false
semver.intersects('< 0.0.x', '0.0.0', { includePrerelease: false }) === false
semver.intersects('< 0', '0.0.x', { includePrerelease: false }) !== false
semver.intersects('< 0.x', '0.0.x', { includePrerelease: false }) !== false
semver.intersects('< 0.0.x', '0.0.x', { includePrerelease: false }) !== false
```

### Environment

- **semver**: [7.3.8](https://www.npmjs.com/package/semver/v/7.3.8)

**Comment by isaacs** [comment]
Technically this should be true if including pre releases, because 0.0.0-0 is less than 0.0.0.

**Comment by sounisi5011** [comment]
> Technically this should be true if including pre releases, because 0.0.0-0 is less than 0.0.0.
> https://github.com/npm/node-semver/issues/521#issuecomment-1475325186

If the `includePrerelease` option is true, then yes. But this behavior does not change whether the `includePrerelease` option is `true` or `false`.

![](https://user-images.githubusercontent.com/6049678/226195388-850ada61-d8a3-46a3-afac-625318075f9f.png)

**Comment by isaacs** [comment]
Yeah, that definitely seems like a bug to me.

**Comment by wraithgar** [comment]
With `includePrerelease` can anything be less than `0.0.0-0`?

**Comment by jakebailey** [comment]
I would assume not; "the rules" say that in prerelease parts, any valid number comes before any valid string, and 0 is the smallest number (negative numbers don't exist 🙈).

**Comment by wraithgar** [comment]
Thanks for confirming, that was my understanding also.

**Comment by wraithgar** [comment]
If `includePrerelease` is `true` and either range is `<0.0.0-0` we always return `false`
If `includePrerelease` is `false` and either range starts with `<0.0.0` we always return `false`

I think that covers everything?

**Comment by wraithgar** [comment]
Found another bug while testing a fix for this:

`semver.intersects('< 0.0.0', '<0.1.x', { includePrerelease: true })`

ends up calling

https://github.com/npm/node-semver/blob/main/ranges/intersects.js#L5

which doesn't pass those options to the `intersects` method itself

**Comment by ljharb** [comment]
nice catch

**Comment by wraithgar** [comment]
https://github.com/npm/node-semver/pull/538
