### ISSUE TITLE
[FEATURE] Add function to compute intersection

### ISSUE THREAD

**Issue by bbrk24** [npm/node-semver#527]
Sometimes, it's useful not just to know whether two ranges intersect, but what the intersection actually is.

I wrote [this implementation](https://github.com/bbrk24/engine-check/blob/master/getIntersection.js), but I haven't tested it that thoroughly yet and I would feel better using a function provided by this library.

**Comment by wraithgar** [comment]
This is not something we have added to our current roadmap.  Folks are welcome to submit implementations with tests.
