### ISSUE TITLE
[BUG] https://semver.npmjs.com does not correctly handle ">" and "||" with pre-release versions

### ISSUE THREAD

**Issue by mikeharder** [npm/node-semver#556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The behavior of https://semver.npmjs.com does not match the `semver` package in the following scenario.

The package claims that `0.44.0-dev.1` should satisfy `>=0.43.0 || >=0.44.0-dev` (which seems correct to me):

```
> semver.satisfies('0.44.0-dev.1', '>=0.43.0 || >=0.44.0-dev')
true
```

It also claims that `0.44.0-dev.1` should be `maxSatisfying()` rather than `0.43.0`:

```
 > semver.maxSatisfying(['0.43.0', '0.44.0-dev.1'], '>=0.43.0 || >=0.44.0-dev')
'0.44.0-dev.1'
```

However, https://semver.npmjs.com does not include the `0.44.0-dev.X` packages in the results for this query (which seems wrong to me):

![image](https://user-images.githubusercontent.com/9459391/235746873-2ca435dd-6b6e-4ee8-99b3-dc4740b6a7ef.png)

And `npm` itself installs `0.43.0` instead of `0.44.0-dev.X` when `package.json` specifies `"@typespec/compiler": ">=0.43.0 || >=0.44.0-dev"`.

### Expected Behavior

https://semver.npmjs.com should include the `0.44.0-dev.X` packages in the results for query `>=0.43.0 || >=0.44.0-dev`.

### Steps To Reproduce

Use https://semver.npmjs.com to query package `@typespec/compiler` for version range `>=0.43.0 || >=0.44.0-dev`.

### Environment

- npm: 8.19.3
- Node: 16.19.1
- OS: Linux
- platform: x64

**Comment by ljharb** [comment]
prereleases aren't included in ranges by default - have you tried `^0.44.0-dev`?

**Comment by mikeharder** [comment]
> prereleases aren't included in ranges by default - have you tried `^0.44.0-dev`?

Using https://semver.npmjs.com, with no `||`, I get the same results for `>=0.44.0-dev` and `^0.44.0-dev`:

![image](https://user-images.githubusercontent.com/9459391/235765941-97e43866-d51c-4c1a-a154-e29ad32c7df5.png)

![image](https://user-images.githubusercontent.com/9459391/235766035-a75089f6-95bc-4937-87b3-f382b3635492.png)

What's strange is if I append `|| >=0.43.0` or `|| ^0.43.0` (to either example), it **reduces** the number of matching versions, which doesn't make logical sense for an "OR" condition:

![image](https://user-images.githubusercontent.com/9459391/235766390-42b9415e-f121-48a7-a35e-56cdbfaab1bc.png)

**Comment by ljharb** [comment]
I agree that for any `x || y` range, if a version is included in x, or in y, it should show up.

Is this an issue with the semver package itself, or just the website? If the latter, this should be closed and you'd need to file an npm ticket.

**Comment by ljharb** [comment]
1 is a bug with the website, which you'd need to report by filing a ticket - this repo isn't for the semver.npmjs.com website.

Re 2, if you want that explored, i'd file it on npm/cli instead of this repo.

**Comment by mikeharder** [comment]
https://github.com/npm/cli/issues/6420
