### ISSUE TITLE
[BUG] Сompare major/minor versions starts with 0

### ISSUE THREAD

**Issue by igor-zima** [npm/node-semver#619]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

if the major/minor versions has more then one number and starts with `0` semver doesn't compare versions trully

### Expected Behavior

it should be work correctly

### Steps To Reproduce

```js
import semver from 'semver';

semver.satisfies('5.01.0', '>=4.93.0') => false
```

```js
import semver from 'semver';

semver.satisfies('5.1.01', '>=4.93.0') => false
```

### Environment

- npm:
- Node: 16/18/20
- OS: windows/linux and mac
- platform:

**Comment by igor-zima** [comment]
help to use option `{loose: true}`

**Comment by ljharb** [comment]
It’s not valid server if one of the parts has a leading zero.
