### ISSUE TITLE
Getting Semver Veracode vulnerability on angular project

### ISSUE THREAD

**Issue by SanthoshReddyTR** [npm/node-semver#639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi Team,
In our project we are getting semver vulnerability when we are updating semver 6.3.1/7.5.2/7.5.4 through,still it is picking 7.3.5 version in veracode scan.
Please find the below details
Angular CLI version 13.2.3
Angular core 13.2.2
Node 14.15.0
After updating node to 14.17.3 also same scan issue.

![image](https://github.com/npm/node-semver/assets/102598539/7bd93ea9-2406-4b26-a831-2718e0297333)
![image](https://github.com/npm/node-semver/assets/102598539/e573101a-71fa-4fe6-b6f7-75475c85c0a4)

### Environment

- npm: 8.13.2
- Node:14.15.0
- OS: Windows
- platform: Dell Latitude 5521

**Comment by wraithgar** [comment]
This does not appear to be an issue w/ semver itself.  There is most likely some dependency in your project that is still requiring an older version of semver.
