### ISSUE TITLE
[BUG?] Remove redundant conditions from `Range`

### ISSUE THREAD

**Issue by bbrk24** [npm/node-semver#676]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`new Range('>=18 || >=18')` keeps the redundant condition, and formats itself as `>=18.0.0||>=18.0.0`

### Expected Behavior

The result should be just `>=18.0.0` -- it should deduplicate the condition

### Steps To Reproduce

```js
const { Range } = require('semver');
console.log(new Range('>=18 || >=18').toString());
```

### Environment

- npm: 10.2.4
- Node: 20.11.0
- OS: Ubuntu 22.04.3 via WSL2 on Windows 11
- platform: x86-64 Windows 11 laptop

**Comment by wraithgar** [comment]
That's not something ranges have ever done.  This would be a new feature, not a bugfix, and would need to be a discrete function that one could call to consolidate a range.  Folks are welcome to submit a PR for consideration but this is not something that's on our roadmap of things to implement.
