### ISSUE TITLE
[BUG] this.build missing from format()

### ISSUE THREAD

**Issue by Bioblaze** [npm/node-semver#685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

format() function does not take into account this.build

### Expected Behavior

when format() is used, if this.build is setup append it too the end of the versioned string.

### Steps To Reproduce

var semver = require("semver")

var version = new semver.SemVer("0.0.0")

version.build = ["dfdsfsdfsdf"]

let newversion = version.format();
console.log(newversion)

### Environment

- npm: all
- Node: all
- OS: all
- platform: all

**Comment by Bioblaze** [comment]
I added a PR for this: https://github.com/npm/node-semver/pull/684

**Comment by wraithgar** [comment]
[PR comment](https://github.com/npm/node-semver/pull/684#issuecomment-2015645709) explains why this is not going to work
