### ISSUE TITLE
[BUG] semver.valid does not reject multiple hyphens in pre-release section

### ISSUE THREAD

**Issue by nektro** [npm/node-semver#686]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```json
{
  "dependencies": {
    "semver": "^7.6.0"
  }
}
```

```js
const semver = require('semver')
console.log(semver.valid('1.2.3-foo-bar'));
```

```
1.2.3-foo-bar
```

### Expected Behavior

```
null
```

### Steps To Reproduce

included above

### Environment

- npm: 10.2.4
- Node: v21.6.2
- OS: Darwin 23.1.0 arm64 macOS 14.1
- platform: darwin

**Comment by ljharb** [comment]
Multiple hyphens are allowed, see https://semver.org/#spec-item-9
