### ISSUE TITLE
[QUESTION] Inconsistent definition of version prefix

### ISSUE THREAD

**Issue by mbtools** [npm/node-semver#690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The readme contains the following about "Versions":

"A leading `"="` or `"v"` character is stripped off and ignored."

Currently, `1.2.3` and `v1.2.3` are valid versions. However, `=1.2.3` is *not* a valid version (it is a valid equal-range).

https://github.com/npm/node-semver/blob/ac9b35769ab0ddfefd5a3af4a3ecaf3da2012352/internal/re.js#L115-L117

### Expected Behavior

`"="` should be added as a valid prefix for versions. 

Versions inside a range allow  `"="`, `"v"`, and `"v="` as prefixes (see #689). It therefore makes sense to allow the same for individual versions.

Suggested change (after #689):

```js
createToken('FULLPLAIN', `v?${src[t.MAINVERSION]}${src[t.PRERELEASE]}?${src[t.BUILD]}?`) // old
createToken('FULLPLAIN', `${src[t.PREFIX]}${src[t.MAINVERSION]}${src[t.PRERELEASE]}?${src[t.BUILD]}?`) // new
```

### Steps To Reproduce

```js
valid('1.2.3') // 1.2.3
valid('v1.2.3') // 1.2.3
valid('=1.2.3') // null
valid('v=1.2.3') // null
```

### Environment

- node-semver: 7.6.0

**Comment by mbtools** [comment]
I fully agree with supporting just `v`

But a) The readme says otherwise, and b) with a range it support `=`/`v=` (and crap like `vv==v`) as well. 

I'm happy to update the docs and #689 to allow only a single, optional `v` in ranges but that's probably a breaking-change. Just comment on #689.

**Comment by wraithgar** [comment]
Oh by all means let's make the docs reflect reality!  Thanks for all the recent PRs.
