### ISSUE TITLE
[BUG] Intersects returns `false` when it shouldn't

### ISSUE THREAD

**Issue by saphewilliam** [npm/node-semver#693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`semver.intersects('~0.19.0', '^0.17.0')` returns `false`

### Expected Behavior

I might be missing something, but as `~0.19.0` means ">=0.19.0 and <0.20.0", and `^0.17.0` means ">=0.17.0 and <1.0.0", and `0.19.0` satisfies both conditions, I'd say that these ranges intersect and the function should return `true`

### Steps To Reproduce

1. Create js file
2. Write `console.log(semver.intersects('~0.19.0', '^0.17.0'))`
3. Run script and observe `false`

### Environment

- npm: 9.8.1
- Node: 18.18.0
- OS: Linux Mint 20.2 Cinnamon 5.0.7
- platform: HP Laptop

**Comment by ljharb** [comment]
You're incorrect. In `vX.Y.Z`, `v0.X.Y`, and `v0.0.X`, X is the major, Y minor, and Z patch.

Thus, v0.18.0 is a _breaking change_ from v0.17.0, and `^` will correctly not update to it.

**Comment by saphewilliam** [comment]
Right! That makes sense. Thanks for your fast reply :)
