### ISSUE TITLE
semver@^6.3.1.: No matching version found for semver@^6.3.1. 

### ISSUE THREAD

**Issue by naim-sajjad** [npm/node-semver#748]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

when i'm running the npm install command for 6.3.1 version it throws an error.
npm i semver@6.3.1

npm ERR! code ETARGET
npm ERR! notarget No matching version found for semver@^6.3.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

### Expected Behavior

it should installed the package succefully.

### Steps To Reproduce

1. simply run npm i semver@6.3.1
2. it will produce the following error
npm ERR! code ETARGET
npm ERR! notarget No matching version found for semver@^6.3.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

### Environment

- npm: 10.9.1
- Node: 18.18.0
- OS: Windows
- platform: Windows

**Comment by awaidqureshi** [comment]
Facing the same issue , Please resolve this ASAP , Our application is stuck.

**Comment by wraithgar** [comment]
This repo is for tracking issues w/ the code in this package itself.

For npm registry issues please contact https://www.npmjs.com/support.
If you think this is a bug in npm itself you can open an issue in https://github.com/npm/cli.
